// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-dub/internal/sdk/models/shared"
	"net/http"
)

type CreateCustomerRequest struct {
	// Email of the customer in the client's app.
	Email *string `json:"email,omitempty"`
	// Name of the customer in the client's app. If not provided, a random name will be generated.
	Name *string `json:"name,omitempty"`
	// Avatar URL of the customer in the client's app.
	Avatar *string `json:"avatar,omitempty"`
	// Unique identifier for the customer in the client's app.
	ExternalID string `json:"externalId"`
}

func (o *CreateCustomerRequest) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *CreateCustomerRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CreateCustomerRequest) GetAvatar() *string {
	if o == nil {
		return nil
	}
	return o.Avatar
}

func (o *CreateCustomerRequest) GetExternalID() string {
	if o == nil {
		return ""
	}
	return o.ExternalID
}

type CreateCustomerLink struct {
	// The unique ID of the short link.
	ID string `json:"id"`
	// The domain of the short link. If not provided, the primary domain for the workspace will be used (or `dub.sh` if the workspace has no domains).
	Domain string `json:"domain"`
	// The short link slug. If not provided, a random 7-character slug will be generated.
	Key string `json:"key"`
	// The full URL of the short link, including the https protocol (e.g. `https://dub.sh/try`).
	ShortLink string `json:"shortLink"`
	// The destination URL of the short link.
	URL string `json:"url"`
	// The ID of the program the short link is associated with.
	ProgramID *string `json:"programId"`
}

func (o *CreateCustomerLink) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateCustomerLink) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}

func (o *CreateCustomerLink) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *CreateCustomerLink) GetShortLink() string {
	if o == nil {
		return ""
	}
	return o.ShortLink
}

func (o *CreateCustomerLink) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *CreateCustomerLink) GetProgramID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramID
}

type CreateCustomerPartner struct {
	// The partner's unique ID on Dub.
	ID string `json:"id"`
	// The partner's full legal name.
	Name string `json:"name"`
	// The partner's email address. Should be a unique value across Dub.
	Email *string `json:"email"`
	// The partner's avatar image.
	Image *string `json:"image"`
}

func (o *CreateCustomerPartner) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateCustomerPartner) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateCustomerPartner) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *CreateCustomerPartner) GetImage() *string {
	if o == nil {
		return nil
	}
	return o.Image
}

type CreateCustomerType string

const (
	CreateCustomerTypePercentage CreateCustomerType = "percentage"
	CreateCustomerTypeFlat       CreateCustomerType = "flat"
)

func (e CreateCustomerType) ToPointer() *CreateCustomerType {
	return &e
}
func (e *CreateCustomerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "percentage":
		fallthrough
	case "flat":
		*e = CreateCustomerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateCustomerType: %v", v)
	}
}

type CreateCustomerDiscount struct {
	ID            string             `json:"id"`
	Amount        float64            `json:"amount"`
	Type          CreateCustomerType `json:"type"`
	MaxDuration   *float64           `json:"maxDuration"`
	Description   *string            `json:"description,omitempty"`
	CouponID      *string            `json:"couponId"`
	CouponTestID  *string            `json:"couponTestId"`
	PartnersCount *float64           `json:"partnersCount,omitempty"`
}

func (o *CreateCustomerDiscount) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateCustomerDiscount) GetAmount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Amount
}

func (o *CreateCustomerDiscount) GetType() CreateCustomerType {
	if o == nil {
		return CreateCustomerType("")
	}
	return o.Type
}

func (o *CreateCustomerDiscount) GetMaxDuration() *float64 {
	if o == nil {
		return nil
	}
	return o.MaxDuration
}

func (o *CreateCustomerDiscount) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateCustomerDiscount) GetCouponID() *string {
	if o == nil {
		return nil
	}
	return o.CouponID
}

func (o *CreateCustomerDiscount) GetCouponTestID() *string {
	if o == nil {
		return nil
	}
	return o.CouponTestID
}

func (o *CreateCustomerDiscount) GetPartnersCount() *float64 {
	if o == nil {
		return nil
	}
	return o.PartnersCount
}

// CreateCustomerResponseBody - The customer was created.
type CreateCustomerResponseBody struct {
	// The unique ID of the customer. You may use either the customer's `id` on Dub (obtained via `/customers` endpoint) or their `externalId` (unique ID within your system, prefixed with `ext_`, e.g. `ext_123`).
	ID string `json:"id"`
	// Unique identifier for the customer in the client's app.
	ExternalID string `json:"externalId"`
	// Name of the customer.
	Name string `json:"name"`
	// Email of the customer.
	Email *string `json:"email,omitempty"`
	// Avatar URL of the customer.
	Avatar *string `json:"avatar,omitempty"`
	// Country of the customer.
	Country *string `json:"country,omitempty"`
	// Total number of sales for the customer.
	Sales *float64 `json:"sales,omitempty"`
	// Total amount of sales for the customer.
	SaleAmount *float64 `json:"saleAmount,omitempty"`
	// The date the customer was created.
	CreatedAt string                  `json:"createdAt"`
	Link      *CreateCustomerLink     `json:"link,omitempty"`
	ProgramID *string                 `json:"programId,omitempty"`
	Partner   *CreateCustomerPartner  `json:"partner,omitempty"`
	Discount  *CreateCustomerDiscount `json:"discount,omitempty"`
}

func (o *CreateCustomerResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateCustomerResponseBody) GetExternalID() string {
	if o == nil {
		return ""
	}
	return o.ExternalID
}

func (o *CreateCustomerResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateCustomerResponseBody) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *CreateCustomerResponseBody) GetAvatar() *string {
	if o == nil {
		return nil
	}
	return o.Avatar
}

func (o *CreateCustomerResponseBody) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *CreateCustomerResponseBody) GetSales() *float64 {
	if o == nil {
		return nil
	}
	return o.Sales
}

func (o *CreateCustomerResponseBody) GetSaleAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.SaleAmount
}

func (o *CreateCustomerResponseBody) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *CreateCustomerResponseBody) GetLink() *CreateCustomerLink {
	if o == nil {
		return nil
	}
	return o.Link
}

func (o *CreateCustomerResponseBody) GetProgramID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramID
}

func (o *CreateCustomerResponseBody) GetPartner() *CreateCustomerPartner {
	if o == nil {
		return nil
	}
	return o.Partner
}

func (o *CreateCustomerResponseBody) GetDiscount() *CreateCustomerDiscount {
	if o == nil {
		return nil
	}
	return o.Discount
}

type CreateCustomerResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The customer was created.
	Object *CreateCustomerResponseBody
	// The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
	FourHundred *shared.FourHundred
	// Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.
	FourHundredAndOne *shared.FourHundredAndOne
	// The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.
	FourHundredAndThree *shared.FourHundredAndThree
	// The server cannot find the requested resource.
	FourHundredAndFour *shared.FourHundredAndFour
	// This response is sent when a request conflicts with the current state of the server.
	FourHundredAndNine *shared.FourHundredAndNine
	// This response is sent when the requested content has been permanently deleted from server, with no forwarding address.
	FourHundredAndTen *shared.FourHundredAndTen
	// The request was well-formed but was unable to be followed due to semantic errors.
	FourHundredAndTwentyTwo *shared.FourHundredAndTwentyTwo
	// The user has sent too many requests in a given amount of time ("rate limiting")
	FourHundredAndTwentyNine *shared.FourHundredAndTwentyNine
	// The server has encountered a situation it does not know how to handle.
	FiveHundred *shared.FiveHundred
}

func (o *CreateCustomerResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateCustomerResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateCustomerResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateCustomerResponse) GetObject() *CreateCustomerResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *CreateCustomerResponse) GetFourHundred() *shared.FourHundred {
	if o == nil {
		return nil
	}
	return o.FourHundred
}

func (o *CreateCustomerResponse) GetFourHundredAndOne() *shared.FourHundredAndOne {
	if o == nil {
		return nil
	}
	return o.FourHundredAndOne
}

func (o *CreateCustomerResponse) GetFourHundredAndThree() *shared.FourHundredAndThree {
	if o == nil {
		return nil
	}
	return o.FourHundredAndThree
}

func (o *CreateCustomerResponse) GetFourHundredAndFour() *shared.FourHundredAndFour {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFour
}

func (o *CreateCustomerResponse) GetFourHundredAndNine() *shared.FourHundredAndNine {
	if o == nil {
		return nil
	}
	return o.FourHundredAndNine
}

func (o *CreateCustomerResponse) GetFourHundredAndTen() *shared.FourHundredAndTen {
	if o == nil {
		return nil
	}
	return o.FourHundredAndTen
}

func (o *CreateCustomerResponse) GetFourHundredAndTwentyTwo() *shared.FourHundredAndTwentyTwo {
	if o == nil {
		return nil
	}
	return o.FourHundredAndTwentyTwo
}

func (o *CreateCustomerResponse) GetFourHundredAndTwentyNine() *shared.FourHundredAndTwentyNine {
	if o == nil {
		return nil
	}
	return o.FourHundredAndTwentyNine
}

func (o *CreateCustomerResponse) GetFiveHundred() *shared.FiveHundred {
	if o == nil {
		return nil
	}
	return o.FiveHundred
}
