// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/speakeasy/terraform-provider-dub/internal/sdk/internal/utils"
	"github.com/speakeasy/terraform-provider-dub/internal/sdk/models/shared"
	"net/http"
)

// RetrieveAnalyticsEvent - The type of event to retrieve analytics for. Defaults to `clicks`.
type RetrieveAnalyticsEvent string

const (
	RetrieveAnalyticsEventClicks    RetrieveAnalyticsEvent = "clicks"
	RetrieveAnalyticsEventLeads     RetrieveAnalyticsEvent = "leads"
	RetrieveAnalyticsEventSales     RetrieveAnalyticsEvent = "sales"
	RetrieveAnalyticsEventComposite RetrieveAnalyticsEvent = "composite"
)

func (e RetrieveAnalyticsEvent) ToPointer() *RetrieveAnalyticsEvent {
	return &e
}
func (e *RetrieveAnalyticsEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "clicks":
		fallthrough
	case "leads":
		fallthrough
	case "sales":
		fallthrough
	case "composite":
		*e = RetrieveAnalyticsEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RetrieveAnalyticsEvent: %v", v)
	}
}

// RetrieveAnalyticsGroupBy - The parameter to group the analytics data points by. Defaults to `count` if undefined.
type RetrieveAnalyticsGroupBy string

const (
	RetrieveAnalyticsGroupByCount        RetrieveAnalyticsGroupBy = "count"
	RetrieveAnalyticsGroupByTimeseries   RetrieveAnalyticsGroupBy = "timeseries"
	RetrieveAnalyticsGroupByContinents   RetrieveAnalyticsGroupBy = "continents"
	RetrieveAnalyticsGroupByRegions      RetrieveAnalyticsGroupBy = "regions"
	RetrieveAnalyticsGroupByCountries    RetrieveAnalyticsGroupBy = "countries"
	RetrieveAnalyticsGroupByCities       RetrieveAnalyticsGroupBy = "cities"
	RetrieveAnalyticsGroupByDevices      RetrieveAnalyticsGroupBy = "devices"
	RetrieveAnalyticsGroupByBrowsers     RetrieveAnalyticsGroupBy = "browsers"
	RetrieveAnalyticsGroupByOs           RetrieveAnalyticsGroupBy = "os"
	RetrieveAnalyticsGroupByTrigger      RetrieveAnalyticsGroupBy = "trigger"
	RetrieveAnalyticsGroupByTriggers     RetrieveAnalyticsGroupBy = "triggers"
	RetrieveAnalyticsGroupByReferers     RetrieveAnalyticsGroupBy = "referers"
	RetrieveAnalyticsGroupByRefererUrls  RetrieveAnalyticsGroupBy = "referer_urls"
	RetrieveAnalyticsGroupByTopPartners  RetrieveAnalyticsGroupBy = "top_partners"
	RetrieveAnalyticsGroupByTopLinks     RetrieveAnalyticsGroupBy = "top_links"
	RetrieveAnalyticsGroupByTopUrls      RetrieveAnalyticsGroupBy = "top_urls"
	RetrieveAnalyticsGroupByUtmSources   RetrieveAnalyticsGroupBy = "utm_sources"
	RetrieveAnalyticsGroupByUtmMediums   RetrieveAnalyticsGroupBy = "utm_mediums"
	RetrieveAnalyticsGroupByUtmCampaigns RetrieveAnalyticsGroupBy = "utm_campaigns"
	RetrieveAnalyticsGroupByUtmTerms     RetrieveAnalyticsGroupBy = "utm_terms"
	RetrieveAnalyticsGroupByUtmContents  RetrieveAnalyticsGroupBy = "utm_contents"
)

func (e RetrieveAnalyticsGroupBy) ToPointer() *RetrieveAnalyticsGroupBy {
	return &e
}
func (e *RetrieveAnalyticsGroupBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "count":
		fallthrough
	case "timeseries":
		fallthrough
	case "continents":
		fallthrough
	case "regions":
		fallthrough
	case "countries":
		fallthrough
	case "cities":
		fallthrough
	case "devices":
		fallthrough
	case "browsers":
		fallthrough
	case "os":
		fallthrough
	case "trigger":
		fallthrough
	case "triggers":
		fallthrough
	case "referers":
		fallthrough
	case "referer_urls":
		fallthrough
	case "top_partners":
		fallthrough
	case "top_links":
		fallthrough
	case "top_urls":
		fallthrough
	case "utm_sources":
		fallthrough
	case "utm_mediums":
		fallthrough
	case "utm_campaigns":
		fallthrough
	case "utm_terms":
		fallthrough
	case "utm_contents":
		*e = RetrieveAnalyticsGroupBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RetrieveAnalyticsGroupBy: %v", v)
	}
}

// RetrieveAnalyticsInterval - The interval to retrieve analytics for. If undefined, defaults to 24h.
type RetrieveAnalyticsInterval string

const (
	RetrieveAnalyticsIntervalTwentyFourh RetrieveAnalyticsInterval = "24h"
	RetrieveAnalyticsIntervalSevend      RetrieveAnalyticsInterval = "7d"
	RetrieveAnalyticsIntervalThirtyd     RetrieveAnalyticsInterval = "30d"
	RetrieveAnalyticsIntervalNinetyd     RetrieveAnalyticsInterval = "90d"
	RetrieveAnalyticsIntervalOney        RetrieveAnalyticsInterval = "1y"
	RetrieveAnalyticsIntervalMtd         RetrieveAnalyticsInterval = "mtd"
	RetrieveAnalyticsIntervalQtd         RetrieveAnalyticsInterval = "qtd"
	RetrieveAnalyticsIntervalYtd         RetrieveAnalyticsInterval = "ytd"
	RetrieveAnalyticsIntervalAll         RetrieveAnalyticsInterval = "all"
)

func (e RetrieveAnalyticsInterval) ToPointer() *RetrieveAnalyticsInterval {
	return &e
}
func (e *RetrieveAnalyticsInterval) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "24h":
		fallthrough
	case "7d":
		fallthrough
	case "30d":
		fallthrough
	case "90d":
		fallthrough
	case "1y":
		fallthrough
	case "mtd":
		fallthrough
	case "qtd":
		fallthrough
	case "ytd":
		fallthrough
	case "all":
		*e = RetrieveAnalyticsInterval(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RetrieveAnalyticsInterval: %v", v)
	}
}

// RetrieveAnalyticsTrigger - The trigger to retrieve analytics for. If undefined, return both QR and link clicks.
type RetrieveAnalyticsTrigger string

const (
	RetrieveAnalyticsTriggerQr   RetrieveAnalyticsTrigger = "qr"
	RetrieveAnalyticsTriggerLink RetrieveAnalyticsTrigger = "link"
)

func (e RetrieveAnalyticsTrigger) ToPointer() *RetrieveAnalyticsTrigger {
	return &e
}
func (e *RetrieveAnalyticsTrigger) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "qr":
		fallthrough
	case "link":
		*e = RetrieveAnalyticsTrigger(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RetrieveAnalyticsTrigger: %v", v)
	}
}

type RetrieveAnalyticsTagIdsType string

const (
	RetrieveAnalyticsTagIdsTypeStr        RetrieveAnalyticsTagIdsType = "str"
	RetrieveAnalyticsTagIdsTypeArrayOfStr RetrieveAnalyticsTagIdsType = "arrayOfStr"
)

// RetrieveAnalyticsTagIds - The tag IDs to retrieve analytics for.
type RetrieveAnalyticsTagIds struct {
	Str        *string  `queryParam:"inline"`
	ArrayOfStr []string `queryParam:"inline"`

	Type RetrieveAnalyticsTagIdsType
}

func CreateRetrieveAnalyticsTagIdsStr(str string) RetrieveAnalyticsTagIds {
	typ := RetrieveAnalyticsTagIdsTypeStr

	return RetrieveAnalyticsTagIds{
		Str:  &str,
		Type: typ,
	}
}

func CreateRetrieveAnalyticsTagIdsArrayOfStr(arrayOfStr []string) RetrieveAnalyticsTagIds {
	typ := RetrieveAnalyticsTagIdsTypeArrayOfStr

	return RetrieveAnalyticsTagIds{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *RetrieveAnalyticsTagIds) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = &str
		u.Type = RetrieveAnalyticsTagIdsTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, true); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = RetrieveAnalyticsTagIdsTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RetrieveAnalyticsTagIds", string(data))
}

func (u RetrieveAnalyticsTagIds) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type RetrieveAnalyticsTagIds: all fields are null")
}

type RetrieveAnalyticsRequest struct {
	// The type of event to retrieve analytics for. Defaults to `clicks`.
	Event *RetrieveAnalyticsEvent `default:"clicks" queryParam:"style=form,explode=true,name=event"`
	// The parameter to group the analytics data points by. Defaults to `count` if undefined.
	GroupBy *RetrieveAnalyticsGroupBy `default:"count" queryParam:"style=form,explode=true,name=groupBy"`
	// The domain to filter analytics for.
	Domain *string `queryParam:"style=form,explode=true,name=domain"`
	// The slug of the short link to retrieve analytics for. Must be used along with the corresponding `domain` of the short link to fetch analytics for a specific short link.
	Key *string `queryParam:"style=form,explode=true,name=key"`
	// The unique ID of the short link on Dub to retrieve analytics for.
	LinkID *string `queryParam:"style=form,explode=true,name=linkId"`
	// The ID of the link in the your database. Must be prefixed with 'ext_' when passed as a query parameter.
	ExternalID *string `queryParam:"style=form,explode=true,name=externalId"`
	// The ID of the tenant that created the link inside your system.
	TenantID *string `queryParam:"style=form,explode=true,name=tenantId"`
	// The ID of the program to retrieve analytics for.
	ProgramID *string `queryParam:"style=form,explode=true,name=programId"`
	// The ID of the partner to retrieve analytics for.
	PartnerID *string `queryParam:"style=form,explode=true,name=partnerId"`
	// The ID of the customer to retrieve analytics for.
	CustomerID *string `queryParam:"style=form,explode=true,name=customerId"`
	// The interval to retrieve analytics for. If undefined, defaults to 24h.
	Interval *RetrieveAnalyticsInterval `queryParam:"style=form,explode=true,name=interval"`
	// The start date and time when to retrieve analytics from. If set, takes precedence over `interval`.
	Start *string `queryParam:"style=form,explode=true,name=start"`
	// The end date and time when to retrieve analytics from. If not provided, defaults to the current date. If set along with `start`, takes precedence over `interval`.
	End *string `queryParam:"style=form,explode=true,name=end"`
	// The IANA time zone code for aligning timeseries granularity (e.g. America/New_York). Defaults to UTC.
	Timezone *string `default:"UTC" queryParam:"style=form,explode=true,name=timezone"`
	// The country to retrieve analytics for.
	Country *shared.CountryCode `queryParam:"style=form,explode=true,name=country"`
	// The city to retrieve analytics for.
	City *string `queryParam:"style=form,explode=true,name=city"`
	// The ISO 3166-2 region code to retrieve analytics for.
	Region *string `queryParam:"style=form,explode=true,name=region"`
	// The continent to retrieve analytics for.
	Continent *shared.ContinentCode `queryParam:"style=form,explode=true,name=continent"`
	// The device to retrieve analytics for.
	Device *string `queryParam:"style=form,explode=true,name=device"`
	// The browser to retrieve analytics for.
	Browser *string `queryParam:"style=form,explode=true,name=browser"`
	// The OS to retrieve analytics for.
	Os *string `queryParam:"style=form,explode=true,name=os"`
	// The trigger to retrieve analytics for. If undefined, return both QR and link clicks.
	Trigger *RetrieveAnalyticsTrigger `queryParam:"style=form,explode=true,name=trigger"`
	// The referer to retrieve analytics for.
	Referer *string `queryParam:"style=form,explode=true,name=referer"`
	// The full referer URL to retrieve analytics for.
	RefererURL *string `queryParam:"style=form,explode=true,name=refererUrl"`
	// The URL to retrieve analytics for.
	URL *string `queryParam:"style=form,explode=true,name=url"`
	// Deprecated. Use `tagIds` instead. The tag ID to retrieve analytics for.
	TagID *string `queryParam:"style=form,explode=true,name=tagId"`
	// The tag IDs to retrieve analytics for.
	TagIds *RetrieveAnalyticsTagIds `queryParam:"style=form,explode=true,name=tagIds"`
	// The folder ID to retrieve analytics for. If not provided, return analytics for unsorted links.
	FolderID *string `queryParam:"style=form,explode=true,name=folderId"`
	// Deprecated. Use the `trigger` field instead. Filter for QR code scans. If true, filter for QR codes only. If false, filter for links only. If undefined, return both.
	Qr *bool `queryParam:"style=form,explode=true,name=qr"`
	// Filter for root domains. If true, filter for domains only. If false, filter for links only. If undefined, return both.
	Root *bool `queryParam:"style=form,explode=true,name=root"`
	// The UTM source of the short link.
	UtmSource *string `queryParam:"style=form,explode=true,name=utm_source"`
	// The UTM medium of the short link.
	UtmMedium *string `queryParam:"style=form,explode=true,name=utm_medium"`
	// The UTM campaign of the short link.
	UtmCampaign *string `queryParam:"style=form,explode=true,name=utm_campaign"`
	// The UTM term of the short link.
	UtmTerm *string `queryParam:"style=form,explode=true,name=utm_term"`
	// The UTM content of the short link.
	UtmContent *string `queryParam:"style=form,explode=true,name=utm_content"`
}

func (r RetrieveAnalyticsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RetrieveAnalyticsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *RetrieveAnalyticsRequest) GetEvent() *RetrieveAnalyticsEvent {
	if o == nil {
		return nil
	}
	return o.Event
}

func (o *RetrieveAnalyticsRequest) GetGroupBy() *RetrieveAnalyticsGroupBy {
	if o == nil {
		return nil
	}
	return o.GroupBy
}

func (o *RetrieveAnalyticsRequest) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *RetrieveAnalyticsRequest) GetKey() *string {
	if o == nil {
		return nil
	}
	return o.Key
}

func (o *RetrieveAnalyticsRequest) GetLinkID() *string {
	if o == nil {
		return nil
	}
	return o.LinkID
}

func (o *RetrieveAnalyticsRequest) GetExternalID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalID
}

func (o *RetrieveAnalyticsRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *RetrieveAnalyticsRequest) GetProgramID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramID
}

func (o *RetrieveAnalyticsRequest) GetPartnerID() *string {
	if o == nil {
		return nil
	}
	return o.PartnerID
}

func (o *RetrieveAnalyticsRequest) GetCustomerID() *string {
	if o == nil {
		return nil
	}
	return o.CustomerID
}

func (o *RetrieveAnalyticsRequest) GetInterval() *RetrieveAnalyticsInterval {
	if o == nil {
		return nil
	}
	return o.Interval
}

func (o *RetrieveAnalyticsRequest) GetStart() *string {
	if o == nil {
		return nil
	}
	return o.Start
}

func (o *RetrieveAnalyticsRequest) GetEnd() *string {
	if o == nil {
		return nil
	}
	return o.End
}

func (o *RetrieveAnalyticsRequest) GetTimezone() *string {
	if o == nil {
		return nil
	}
	return o.Timezone
}

func (o *RetrieveAnalyticsRequest) GetCountry() *shared.CountryCode {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *RetrieveAnalyticsRequest) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *RetrieveAnalyticsRequest) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *RetrieveAnalyticsRequest) GetContinent() *shared.ContinentCode {
	if o == nil {
		return nil
	}
	return o.Continent
}

func (o *RetrieveAnalyticsRequest) GetDevice() *string {
	if o == nil {
		return nil
	}
	return o.Device
}

func (o *RetrieveAnalyticsRequest) GetBrowser() *string {
	if o == nil {
		return nil
	}
	return o.Browser
}

func (o *RetrieveAnalyticsRequest) GetOs() *string {
	if o == nil {
		return nil
	}
	return o.Os
}

func (o *RetrieveAnalyticsRequest) GetTrigger() *RetrieveAnalyticsTrigger {
	if o == nil {
		return nil
	}
	return o.Trigger
}

func (o *RetrieveAnalyticsRequest) GetReferer() *string {
	if o == nil {
		return nil
	}
	return o.Referer
}

func (o *RetrieveAnalyticsRequest) GetRefererURL() *string {
	if o == nil {
		return nil
	}
	return o.RefererURL
}

func (o *RetrieveAnalyticsRequest) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *RetrieveAnalyticsRequest) GetTagID() *string {
	if o == nil {
		return nil
	}
	return o.TagID
}

func (o *RetrieveAnalyticsRequest) GetTagIds() *RetrieveAnalyticsTagIds {
	if o == nil {
		return nil
	}
	return o.TagIds
}

func (o *RetrieveAnalyticsRequest) GetFolderID() *string {
	if o == nil {
		return nil
	}
	return o.FolderID
}

func (o *RetrieveAnalyticsRequest) GetQr() *bool {
	if o == nil {
		return nil
	}
	return o.Qr
}

func (o *RetrieveAnalyticsRequest) GetRoot() *bool {
	if o == nil {
		return nil
	}
	return o.Root
}

func (o *RetrieveAnalyticsRequest) GetUtmSource() *string {
	if o == nil {
		return nil
	}
	return o.UtmSource
}

func (o *RetrieveAnalyticsRequest) GetUtmMedium() *string {
	if o == nil {
		return nil
	}
	return o.UtmMedium
}

func (o *RetrieveAnalyticsRequest) GetUtmCampaign() *string {
	if o == nil {
		return nil
	}
	return o.UtmCampaign
}

func (o *RetrieveAnalyticsRequest) GetUtmTerm() *string {
	if o == nil {
		return nil
	}
	return o.UtmTerm
}

func (o *RetrieveAnalyticsRequest) GetUtmContent() *string {
	if o == nil {
		return nil
	}
	return o.UtmContent
}

type RetrieveAnalyticsResponseBodyType string

const (
	RetrieveAnalyticsResponseBodyTypeAnalyticsCount              RetrieveAnalyticsResponseBodyType = "AnalyticsCount"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTimeseries  RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsTimeseries"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsContinents  RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsContinents"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsCountries   RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsCountries"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsRegions     RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsRegions"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsCities      RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsCities"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsDevices     RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsDevices"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsBrowsers    RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsBrowsers"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsOS          RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsOS"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTriggers    RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsTriggers"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsReferers    RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsReferers"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsRefererUrls RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsRefererUrls"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTopLinks    RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsTopLinks"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTopUrls     RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsTopUrls"
)

// RetrieveAnalyticsResponseBody - Analytics data
type RetrieveAnalyticsResponseBody struct {
	AnalyticsCount              *shared.AnalyticsCount        `queryParam:"inline"`
	ArrayOfAnalyticsTimeseries  []shared.AnalyticsTimeseries  `queryParam:"inline"`
	ArrayOfAnalyticsContinents  []shared.AnalyticsContinents  `queryParam:"inline"`
	ArrayOfAnalyticsCountries   []shared.AnalyticsCountries   `queryParam:"inline"`
	ArrayOfAnalyticsRegions     []shared.AnalyticsRegions     `queryParam:"inline"`
	ArrayOfAnalyticsCities      []shared.AnalyticsCities      `queryParam:"inline"`
	ArrayOfAnalyticsDevices     []shared.AnalyticsDevices     `queryParam:"inline"`
	ArrayOfAnalyticsBrowsers    []shared.AnalyticsBrowsers    `queryParam:"inline"`
	ArrayOfAnalyticsOS          []shared.AnalyticsOS          `queryParam:"inline"`
	ArrayOfAnalyticsTriggers    []shared.AnalyticsTriggers    `queryParam:"inline"`
	ArrayOfAnalyticsReferers    []shared.AnalyticsReferers    `queryParam:"inline"`
	ArrayOfAnalyticsRefererUrls []shared.AnalyticsRefererUrls `queryParam:"inline"`
	ArrayOfAnalyticsTopLinks    []shared.AnalyticsTopLinks    `queryParam:"inline"`
	ArrayOfAnalyticsTopUrls     []shared.AnalyticsTopUrls     `queryParam:"inline"`

	Type RetrieveAnalyticsResponseBodyType
}

func CreateRetrieveAnalyticsResponseBodyAnalyticsCount(analyticsCount shared.AnalyticsCount) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeAnalyticsCount

	return RetrieveAnalyticsResponseBody{
		AnalyticsCount: &analyticsCount,
		Type:           typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsTimeseries(arrayOfAnalyticsTimeseries []shared.AnalyticsTimeseries) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTimeseries

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsTimeseries: arrayOfAnalyticsTimeseries,
		Type:                       typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsContinents(arrayOfAnalyticsContinents []shared.AnalyticsContinents) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsContinents

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsContinents: arrayOfAnalyticsContinents,
		Type:                       typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsCountries(arrayOfAnalyticsCountries []shared.AnalyticsCountries) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsCountries

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsCountries: arrayOfAnalyticsCountries,
		Type:                      typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsRegions(arrayOfAnalyticsRegions []shared.AnalyticsRegions) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsRegions

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsRegions: arrayOfAnalyticsRegions,
		Type:                    typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsCities(arrayOfAnalyticsCities []shared.AnalyticsCities) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsCities

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsCities: arrayOfAnalyticsCities,
		Type:                   typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsDevices(arrayOfAnalyticsDevices []shared.AnalyticsDevices) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsDevices

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsDevices: arrayOfAnalyticsDevices,
		Type:                    typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsBrowsers(arrayOfAnalyticsBrowsers []shared.AnalyticsBrowsers) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsBrowsers

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsBrowsers: arrayOfAnalyticsBrowsers,
		Type:                     typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsOS(arrayOfAnalyticsOS []shared.AnalyticsOS) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsOS

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsOS: arrayOfAnalyticsOS,
		Type:               typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsTriggers(arrayOfAnalyticsTriggers []shared.AnalyticsTriggers) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTriggers

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsTriggers: arrayOfAnalyticsTriggers,
		Type:                     typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsReferers(arrayOfAnalyticsReferers []shared.AnalyticsReferers) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsReferers

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsReferers: arrayOfAnalyticsReferers,
		Type:                     typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsRefererUrls(arrayOfAnalyticsRefererUrls []shared.AnalyticsRefererUrls) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsRefererUrls

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsRefererUrls: arrayOfAnalyticsRefererUrls,
		Type:                        typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsTopLinks(arrayOfAnalyticsTopLinks []shared.AnalyticsTopLinks) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTopLinks

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsTopLinks: arrayOfAnalyticsTopLinks,
		Type:                     typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsTopUrls(arrayOfAnalyticsTopUrls []shared.AnalyticsTopUrls) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTopUrls

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsTopUrls: arrayOfAnalyticsTopUrls,
		Type:                    typ,
	}
}

func (u *RetrieveAnalyticsResponseBody) UnmarshalJSON(data []byte) error {

	var analyticsCount shared.AnalyticsCount = shared.AnalyticsCount{}
	if err := utils.UnmarshalJSON(data, &analyticsCount, "", true, true); err == nil {
		u.AnalyticsCount = &analyticsCount
		u.Type = RetrieveAnalyticsResponseBodyTypeAnalyticsCount
		return nil
	}

	var arrayOfAnalyticsTimeseries []shared.AnalyticsTimeseries = []shared.AnalyticsTimeseries{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsTimeseries, "", true, true); err == nil {
		u.ArrayOfAnalyticsTimeseries = arrayOfAnalyticsTimeseries
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTimeseries
		return nil
	}

	var arrayOfAnalyticsContinents []shared.AnalyticsContinents = []shared.AnalyticsContinents{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsContinents, "", true, true); err == nil {
		u.ArrayOfAnalyticsContinents = arrayOfAnalyticsContinents
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsContinents
		return nil
	}

	var arrayOfAnalyticsCountries []shared.AnalyticsCountries = []shared.AnalyticsCountries{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsCountries, "", true, true); err == nil {
		u.ArrayOfAnalyticsCountries = arrayOfAnalyticsCountries
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsCountries
		return nil
	}

	var arrayOfAnalyticsRegions []shared.AnalyticsRegions = []shared.AnalyticsRegions{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsRegions, "", true, true); err == nil {
		u.ArrayOfAnalyticsRegions = arrayOfAnalyticsRegions
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsRegions
		return nil
	}

	var arrayOfAnalyticsCities []shared.AnalyticsCities = []shared.AnalyticsCities{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsCities, "", true, true); err == nil {
		u.ArrayOfAnalyticsCities = arrayOfAnalyticsCities
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsCities
		return nil
	}

	var arrayOfAnalyticsDevices []shared.AnalyticsDevices = []shared.AnalyticsDevices{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsDevices, "", true, true); err == nil {
		u.ArrayOfAnalyticsDevices = arrayOfAnalyticsDevices
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsDevices
		return nil
	}

	var arrayOfAnalyticsBrowsers []shared.AnalyticsBrowsers = []shared.AnalyticsBrowsers{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsBrowsers, "", true, true); err == nil {
		u.ArrayOfAnalyticsBrowsers = arrayOfAnalyticsBrowsers
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsBrowsers
		return nil
	}

	var arrayOfAnalyticsOS []shared.AnalyticsOS = []shared.AnalyticsOS{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsOS, "", true, true); err == nil {
		u.ArrayOfAnalyticsOS = arrayOfAnalyticsOS
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsOS
		return nil
	}

	var arrayOfAnalyticsTriggers []shared.AnalyticsTriggers = []shared.AnalyticsTriggers{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsTriggers, "", true, true); err == nil {
		u.ArrayOfAnalyticsTriggers = arrayOfAnalyticsTriggers
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTriggers
		return nil
	}

	var arrayOfAnalyticsReferers []shared.AnalyticsReferers = []shared.AnalyticsReferers{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsReferers, "", true, true); err == nil {
		u.ArrayOfAnalyticsReferers = arrayOfAnalyticsReferers
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsReferers
		return nil
	}

	var arrayOfAnalyticsRefererUrls []shared.AnalyticsRefererUrls = []shared.AnalyticsRefererUrls{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsRefererUrls, "", true, true); err == nil {
		u.ArrayOfAnalyticsRefererUrls = arrayOfAnalyticsRefererUrls
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsRefererUrls
		return nil
	}

	var arrayOfAnalyticsTopLinks []shared.AnalyticsTopLinks = []shared.AnalyticsTopLinks{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsTopLinks, "", true, true); err == nil {
		u.ArrayOfAnalyticsTopLinks = arrayOfAnalyticsTopLinks
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTopLinks
		return nil
	}

	var arrayOfAnalyticsTopUrls []shared.AnalyticsTopUrls = []shared.AnalyticsTopUrls{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsTopUrls, "", true, true); err == nil {
		u.ArrayOfAnalyticsTopUrls = arrayOfAnalyticsTopUrls
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTopUrls
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RetrieveAnalyticsResponseBody", string(data))
}

func (u RetrieveAnalyticsResponseBody) MarshalJSON() ([]byte, error) {
	if u.AnalyticsCount != nil {
		return utils.MarshalJSON(u.AnalyticsCount, "", true)
	}

	if u.ArrayOfAnalyticsTimeseries != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsTimeseries, "", true)
	}

	if u.ArrayOfAnalyticsContinents != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsContinents, "", true)
	}

	if u.ArrayOfAnalyticsCountries != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsCountries, "", true)
	}

	if u.ArrayOfAnalyticsRegions != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsRegions, "", true)
	}

	if u.ArrayOfAnalyticsCities != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsCities, "", true)
	}

	if u.ArrayOfAnalyticsDevices != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsDevices, "", true)
	}

	if u.ArrayOfAnalyticsBrowsers != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsBrowsers, "", true)
	}

	if u.ArrayOfAnalyticsOS != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsOS, "", true)
	}

	if u.ArrayOfAnalyticsTriggers != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsTriggers, "", true)
	}

	if u.ArrayOfAnalyticsReferers != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsReferers, "", true)
	}

	if u.ArrayOfAnalyticsRefererUrls != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsRefererUrls, "", true)
	}

	if u.ArrayOfAnalyticsTopLinks != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsTopLinks, "", true)
	}

	if u.ArrayOfAnalyticsTopUrls != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsTopUrls, "", true)
	}

	return nil, errors.New("could not marshal union type RetrieveAnalyticsResponseBody: all fields are null")
}

type RetrieveAnalyticsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Analytics data
	OneOf *RetrieveAnalyticsResponseBody
	// The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
	FourHundred *shared.FourHundred
	// Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.
	FourHundredAndOne *shared.FourHundredAndOne
	// The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.
	FourHundredAndThree *shared.FourHundredAndThree
	// The server cannot find the requested resource.
	FourHundredAndFour *shared.FourHundredAndFour
	// This response is sent when a request conflicts with the current state of the server.
	FourHundredAndNine *shared.FourHundredAndNine
	// This response is sent when the requested content has been permanently deleted from server, with no forwarding address.
	FourHundredAndTen *shared.FourHundredAndTen
	// The request was well-formed but was unable to be followed due to semantic errors.
	FourHundredAndTwentyTwo *shared.FourHundredAndTwentyTwo
	// The user has sent too many requests in a given amount of time ("rate limiting")
	FourHundredAndTwentyNine *shared.FourHundredAndTwentyNine
	// The server has encountered a situation it does not know how to handle.
	FiveHundred *shared.FiveHundred
}

func (o *RetrieveAnalyticsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RetrieveAnalyticsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RetrieveAnalyticsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RetrieveAnalyticsResponse) GetOneOf() *RetrieveAnalyticsResponseBody {
	if o == nil {
		return nil
	}
	return o.OneOf
}

func (o *RetrieveAnalyticsResponse) GetFourHundred() *shared.FourHundred {
	if o == nil {
		return nil
	}
	return o.FourHundred
}

func (o *RetrieveAnalyticsResponse) GetFourHundredAndOne() *shared.FourHundredAndOne {
	if o == nil {
		return nil
	}
	return o.FourHundredAndOne
}

func (o *RetrieveAnalyticsResponse) GetFourHundredAndThree() *shared.FourHundredAndThree {
	if o == nil {
		return nil
	}
	return o.FourHundredAndThree
}

func (o *RetrieveAnalyticsResponse) GetFourHundredAndFour() *shared.FourHundredAndFour {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFour
}

func (o *RetrieveAnalyticsResponse) GetFourHundredAndNine() *shared.FourHundredAndNine {
	if o == nil {
		return nil
	}
	return o.FourHundredAndNine
}

func (o *RetrieveAnalyticsResponse) GetFourHundredAndTen() *shared.FourHundredAndTen {
	if o == nil {
		return nil
	}
	return o.FourHundredAndTen
}

func (o *RetrieveAnalyticsResponse) GetFourHundredAndTwentyTwo() *shared.FourHundredAndTwentyTwo {
	if o == nil {
		return nil
	}
	return o.FourHundredAndTwentyTwo
}

func (o *RetrieveAnalyticsResponse) GetFourHundredAndTwentyNine() *shared.FourHundredAndTwentyNine {
	if o == nil {
		return nil
	}
	return o.FourHundredAndTwentyNine
}

func (o *RetrieveAnalyticsResponse) GetFiveHundred() *shared.FiveHundred {
	if o == nil {
		return nil
	}
	return o.FiveHundred
}
