// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-dub/internal/sdk/models/shared"
	"net/http"
)

type UpdateCustomerRequestBody struct {
	// Email of the customer in the client's app.
	Email *string `json:"email,omitempty"`
	// Name of the customer in the client's app. If not provided, a random name will be generated.
	Name *string `json:"name,omitempty"`
	// Avatar URL of the customer in the client's app.
	Avatar *string `json:"avatar,omitempty"`
	// Unique identifier for the customer in the client's app.
	ExternalID *string `json:"externalId,omitempty"`
}

func (o *UpdateCustomerRequestBody) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UpdateCustomerRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateCustomerRequestBody) GetAvatar() *string {
	if o == nil {
		return nil
	}
	return o.Avatar
}

func (o *UpdateCustomerRequestBody) GetExternalID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalID
}

type UpdateCustomerRequest struct {
	// The unique ID of the customer. You may use either the customer's `id` on Dub (obtained via `/customers` endpoint) or their `externalId` (unique ID within your system, prefixed with `ext_`, e.g. `ext_123`).
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Whether to include expanded fields on the customer (`link`, `partner`, `discount`).
	IncludeExpandedFields *bool                      `queryParam:"style=form,explode=true,name=includeExpandedFields"`
	RequestBody           *UpdateCustomerRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateCustomerRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateCustomerRequest) GetIncludeExpandedFields() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeExpandedFields
}

func (o *UpdateCustomerRequest) GetRequestBody() *UpdateCustomerRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type UpdateCustomerLink struct {
	// The unique ID of the short link.
	ID string `json:"id"`
	// The domain of the short link. If not provided, the primary domain for the workspace will be used (or `dub.sh` if the workspace has no domains).
	Domain string `json:"domain"`
	// The short link slug. If not provided, a random 7-character slug will be generated.
	Key string `json:"key"`
	// The full URL of the short link, including the https protocol (e.g. `https://dub.sh/try`).
	ShortLink string `json:"shortLink"`
	// The destination URL of the short link.
	URL string `json:"url"`
	// The ID of the program the short link is associated with.
	ProgramID *string `json:"programId"`
}

func (o *UpdateCustomerLink) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateCustomerLink) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}

func (o *UpdateCustomerLink) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *UpdateCustomerLink) GetShortLink() string {
	if o == nil {
		return ""
	}
	return o.ShortLink
}

func (o *UpdateCustomerLink) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *UpdateCustomerLink) GetProgramID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramID
}

type UpdateCustomerPartner struct {
	// The partner's unique ID on Dub.
	ID string `json:"id"`
	// The partner's full legal name.
	Name string `json:"name"`
	// The partner's email address. Should be a unique value across Dub.
	Email *string `json:"email"`
	// The partner's avatar image.
	Image *string `json:"image"`
}

func (o *UpdateCustomerPartner) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateCustomerPartner) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UpdateCustomerPartner) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UpdateCustomerPartner) GetImage() *string {
	if o == nil {
		return nil
	}
	return o.Image
}

type UpdateCustomerType string

const (
	UpdateCustomerTypePercentage UpdateCustomerType = "percentage"
	UpdateCustomerTypeFlat       UpdateCustomerType = "flat"
)

func (e UpdateCustomerType) ToPointer() *UpdateCustomerType {
	return &e
}
func (e *UpdateCustomerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "percentage":
		fallthrough
	case "flat":
		*e = UpdateCustomerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateCustomerType: %v", v)
	}
}

type UpdateCustomerDiscount struct {
	ID            string             `json:"id"`
	Amount        float64            `json:"amount"`
	Type          UpdateCustomerType `json:"type"`
	MaxDuration   *float64           `json:"maxDuration"`
	Description   *string            `json:"description,omitempty"`
	CouponID      *string            `json:"couponId"`
	CouponTestID  *string            `json:"couponTestId"`
	PartnersCount *float64           `json:"partnersCount,omitempty"`
}

func (o *UpdateCustomerDiscount) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateCustomerDiscount) GetAmount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Amount
}

func (o *UpdateCustomerDiscount) GetType() UpdateCustomerType {
	if o == nil {
		return UpdateCustomerType("")
	}
	return o.Type
}

func (o *UpdateCustomerDiscount) GetMaxDuration() *float64 {
	if o == nil {
		return nil
	}
	return o.MaxDuration
}

func (o *UpdateCustomerDiscount) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateCustomerDiscount) GetCouponID() *string {
	if o == nil {
		return nil
	}
	return o.CouponID
}

func (o *UpdateCustomerDiscount) GetCouponTestID() *string {
	if o == nil {
		return nil
	}
	return o.CouponTestID
}

func (o *UpdateCustomerDiscount) GetPartnersCount() *float64 {
	if o == nil {
		return nil
	}
	return o.PartnersCount
}

// UpdateCustomerResponseBody - The customer was updated.
type UpdateCustomerResponseBody struct {
	// The unique ID of the customer. You may use either the customer's `id` on Dub (obtained via `/customers` endpoint) or their `externalId` (unique ID within your system, prefixed with `ext_`, e.g. `ext_123`).
	ID string `json:"id"`
	// Unique identifier for the customer in the client's app.
	ExternalID string `json:"externalId"`
	// Name of the customer.
	Name string `json:"name"`
	// Email of the customer.
	Email *string `json:"email,omitempty"`
	// Avatar URL of the customer.
	Avatar *string `json:"avatar,omitempty"`
	// Country of the customer.
	Country *string `json:"country,omitempty"`
	// Total number of sales for the customer.
	Sales *float64 `json:"sales,omitempty"`
	// Total amount of sales for the customer.
	SaleAmount *float64 `json:"saleAmount,omitempty"`
	// The date the customer was created.
	CreatedAt string                  `json:"createdAt"`
	Link      *UpdateCustomerLink     `json:"link,omitempty"`
	ProgramID *string                 `json:"programId,omitempty"`
	Partner   *UpdateCustomerPartner  `json:"partner,omitempty"`
	Discount  *UpdateCustomerDiscount `json:"discount,omitempty"`
}

func (o *UpdateCustomerResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateCustomerResponseBody) GetExternalID() string {
	if o == nil {
		return ""
	}
	return o.ExternalID
}

func (o *UpdateCustomerResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UpdateCustomerResponseBody) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UpdateCustomerResponseBody) GetAvatar() *string {
	if o == nil {
		return nil
	}
	return o.Avatar
}

func (o *UpdateCustomerResponseBody) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *UpdateCustomerResponseBody) GetSales() *float64 {
	if o == nil {
		return nil
	}
	return o.Sales
}

func (o *UpdateCustomerResponseBody) GetSaleAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.SaleAmount
}

func (o *UpdateCustomerResponseBody) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *UpdateCustomerResponseBody) GetLink() *UpdateCustomerLink {
	if o == nil {
		return nil
	}
	return o.Link
}

func (o *UpdateCustomerResponseBody) GetProgramID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramID
}

func (o *UpdateCustomerResponseBody) GetPartner() *UpdateCustomerPartner {
	if o == nil {
		return nil
	}
	return o.Partner
}

func (o *UpdateCustomerResponseBody) GetDiscount() *UpdateCustomerDiscount {
	if o == nil {
		return nil
	}
	return o.Discount
}

type UpdateCustomerResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The customer was updated.
	Object *UpdateCustomerResponseBody
	// The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
	FourHundred *shared.FourHundred
	// Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.
	FourHundredAndOne *shared.FourHundredAndOne
	// The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.
	FourHundredAndThree *shared.FourHundredAndThree
	// The server cannot find the requested resource.
	FourHundredAndFour *shared.FourHundredAndFour
	// This response is sent when a request conflicts with the current state of the server.
	FourHundredAndNine *shared.FourHundredAndNine
	// This response is sent when the requested content has been permanently deleted from server, with no forwarding address.
	FourHundredAndTen *shared.FourHundredAndTen
	// The request was well-formed but was unable to be followed due to semantic errors.
	FourHundredAndTwentyTwo *shared.FourHundredAndTwentyTwo
	// The user has sent too many requests in a given amount of time ("rate limiting")
	FourHundredAndTwentyNine *shared.FourHundredAndTwentyNine
	// The server has encountered a situation it does not know how to handle.
	FiveHundred *shared.FiveHundred
}

func (o *UpdateCustomerResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateCustomerResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateCustomerResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateCustomerResponse) GetObject() *UpdateCustomerResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *UpdateCustomerResponse) GetFourHundred() *shared.FourHundred {
	if o == nil {
		return nil
	}
	return o.FourHundred
}

func (o *UpdateCustomerResponse) GetFourHundredAndOne() *shared.FourHundredAndOne {
	if o == nil {
		return nil
	}
	return o.FourHundredAndOne
}

func (o *UpdateCustomerResponse) GetFourHundredAndThree() *shared.FourHundredAndThree {
	if o == nil {
		return nil
	}
	return o.FourHundredAndThree
}

func (o *UpdateCustomerResponse) GetFourHundredAndFour() *shared.FourHundredAndFour {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFour
}

func (o *UpdateCustomerResponse) GetFourHundredAndNine() *shared.FourHundredAndNine {
	if o == nil {
		return nil
	}
	return o.FourHundredAndNine
}

func (o *UpdateCustomerResponse) GetFourHundredAndTen() *shared.FourHundredAndTen {
	if o == nil {
		return nil
	}
	return o.FourHundredAndTen
}

func (o *UpdateCustomerResponse) GetFourHundredAndTwentyTwo() *shared.FourHundredAndTwentyTwo {
	if o == nil {
		return nil
	}
	return o.FourHundredAndTwentyTwo
}

func (o *UpdateCustomerResponse) GetFourHundredAndTwentyNine() *shared.FourHundredAndTwentyNine {
	if o == nil {
		return nil
	}
	return o.FourHundredAndTwentyNine
}

func (o *UpdateCustomerResponse) GetFiveHundred() *shared.FiveHundred {
	if o == nil {
		return nil
	}
	return o.FiveHundred
}
