// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-dub/internal/sdk/internal/utils"
)

// AnalyticsCountriesCountry - The 2-letter ISO 3166-1 country code for the country associated with the location of the user. Learn more: https://d.to/geo
type AnalyticsCountriesCountry string

const (
	AnalyticsCountriesCountryAf AnalyticsCountriesCountry = "AF"
	AnalyticsCountriesCountryAl AnalyticsCountriesCountry = "AL"
	AnalyticsCountriesCountryDz AnalyticsCountriesCountry = "DZ"
	AnalyticsCountriesCountryAs AnalyticsCountriesCountry = "AS"
	AnalyticsCountriesCountryAd AnalyticsCountriesCountry = "AD"
	AnalyticsCountriesCountryAo AnalyticsCountriesCountry = "AO"
	AnalyticsCountriesCountryAi AnalyticsCountriesCountry = "AI"
	AnalyticsCountriesCountryAq AnalyticsCountriesCountry = "AQ"
	AnalyticsCountriesCountryAg AnalyticsCountriesCountry = "AG"
	AnalyticsCountriesCountryAr AnalyticsCountriesCountry = "AR"
	AnalyticsCountriesCountryAm AnalyticsCountriesCountry = "AM"
	AnalyticsCountriesCountryAw AnalyticsCountriesCountry = "AW"
	AnalyticsCountriesCountryAu AnalyticsCountriesCountry = "AU"
	AnalyticsCountriesCountryAt AnalyticsCountriesCountry = "AT"
	AnalyticsCountriesCountryAz AnalyticsCountriesCountry = "AZ"
	AnalyticsCountriesCountryBs AnalyticsCountriesCountry = "BS"
	AnalyticsCountriesCountryBh AnalyticsCountriesCountry = "BH"
	AnalyticsCountriesCountryBd AnalyticsCountriesCountry = "BD"
	AnalyticsCountriesCountryBb AnalyticsCountriesCountry = "BB"
	AnalyticsCountriesCountryBy AnalyticsCountriesCountry = "BY"
	AnalyticsCountriesCountryBe AnalyticsCountriesCountry = "BE"
	AnalyticsCountriesCountryBz AnalyticsCountriesCountry = "BZ"
	AnalyticsCountriesCountryBj AnalyticsCountriesCountry = "BJ"
	AnalyticsCountriesCountryBm AnalyticsCountriesCountry = "BM"
	AnalyticsCountriesCountryBt AnalyticsCountriesCountry = "BT"
	AnalyticsCountriesCountryBo AnalyticsCountriesCountry = "BO"
	AnalyticsCountriesCountryBa AnalyticsCountriesCountry = "BA"
	AnalyticsCountriesCountryBw AnalyticsCountriesCountry = "BW"
	AnalyticsCountriesCountryBv AnalyticsCountriesCountry = "BV"
	AnalyticsCountriesCountryBr AnalyticsCountriesCountry = "BR"
	AnalyticsCountriesCountryIo AnalyticsCountriesCountry = "IO"
	AnalyticsCountriesCountryBn AnalyticsCountriesCountry = "BN"
	AnalyticsCountriesCountryBg AnalyticsCountriesCountry = "BG"
	AnalyticsCountriesCountryBf AnalyticsCountriesCountry = "BF"
	AnalyticsCountriesCountryBi AnalyticsCountriesCountry = "BI"
	AnalyticsCountriesCountryKh AnalyticsCountriesCountry = "KH"
	AnalyticsCountriesCountryCm AnalyticsCountriesCountry = "CM"
	AnalyticsCountriesCountryCa AnalyticsCountriesCountry = "CA"
	AnalyticsCountriesCountryCv AnalyticsCountriesCountry = "CV"
	AnalyticsCountriesCountryKy AnalyticsCountriesCountry = "KY"
	AnalyticsCountriesCountryCf AnalyticsCountriesCountry = "CF"
	AnalyticsCountriesCountryTd AnalyticsCountriesCountry = "TD"
	AnalyticsCountriesCountryCl AnalyticsCountriesCountry = "CL"
	AnalyticsCountriesCountryCn AnalyticsCountriesCountry = "CN"
	AnalyticsCountriesCountryCx AnalyticsCountriesCountry = "CX"
	AnalyticsCountriesCountryCc AnalyticsCountriesCountry = "CC"
	AnalyticsCountriesCountryCo AnalyticsCountriesCountry = "CO"
	AnalyticsCountriesCountryKm AnalyticsCountriesCountry = "KM"
	AnalyticsCountriesCountryCg AnalyticsCountriesCountry = "CG"
	AnalyticsCountriesCountryCd AnalyticsCountriesCountry = "CD"
	AnalyticsCountriesCountryCk AnalyticsCountriesCountry = "CK"
	AnalyticsCountriesCountryCr AnalyticsCountriesCountry = "CR"
	AnalyticsCountriesCountryCi AnalyticsCountriesCountry = "CI"
	AnalyticsCountriesCountryHr AnalyticsCountriesCountry = "HR"
	AnalyticsCountriesCountryCu AnalyticsCountriesCountry = "CU"
	AnalyticsCountriesCountryCy AnalyticsCountriesCountry = "CY"
	AnalyticsCountriesCountryCz AnalyticsCountriesCountry = "CZ"
	AnalyticsCountriesCountryDk AnalyticsCountriesCountry = "DK"
	AnalyticsCountriesCountryDj AnalyticsCountriesCountry = "DJ"
	AnalyticsCountriesCountryDm AnalyticsCountriesCountry = "DM"
	AnalyticsCountriesCountryDo AnalyticsCountriesCountry = "DO"
	AnalyticsCountriesCountryEc AnalyticsCountriesCountry = "EC"
	AnalyticsCountriesCountryEg AnalyticsCountriesCountry = "EG"
	AnalyticsCountriesCountrySv AnalyticsCountriesCountry = "SV"
	AnalyticsCountriesCountryGq AnalyticsCountriesCountry = "GQ"
	AnalyticsCountriesCountryEr AnalyticsCountriesCountry = "ER"
	AnalyticsCountriesCountryEe AnalyticsCountriesCountry = "EE"
	AnalyticsCountriesCountryEt AnalyticsCountriesCountry = "ET"
	AnalyticsCountriesCountryFk AnalyticsCountriesCountry = "FK"
	AnalyticsCountriesCountryFo AnalyticsCountriesCountry = "FO"
	AnalyticsCountriesCountryFj AnalyticsCountriesCountry = "FJ"
	AnalyticsCountriesCountryFi AnalyticsCountriesCountry = "FI"
	AnalyticsCountriesCountryFr AnalyticsCountriesCountry = "FR"
	AnalyticsCountriesCountryGf AnalyticsCountriesCountry = "GF"
	AnalyticsCountriesCountryPf AnalyticsCountriesCountry = "PF"
	AnalyticsCountriesCountryTf AnalyticsCountriesCountry = "TF"
	AnalyticsCountriesCountryGa AnalyticsCountriesCountry = "GA"
	AnalyticsCountriesCountryGm AnalyticsCountriesCountry = "GM"
	AnalyticsCountriesCountryGe AnalyticsCountriesCountry = "GE"
	AnalyticsCountriesCountryDe AnalyticsCountriesCountry = "DE"
	AnalyticsCountriesCountryGh AnalyticsCountriesCountry = "GH"
	AnalyticsCountriesCountryGi AnalyticsCountriesCountry = "GI"
	AnalyticsCountriesCountryGr AnalyticsCountriesCountry = "GR"
	AnalyticsCountriesCountryGl AnalyticsCountriesCountry = "GL"
	AnalyticsCountriesCountryGd AnalyticsCountriesCountry = "GD"
	AnalyticsCountriesCountryGp AnalyticsCountriesCountry = "GP"
	AnalyticsCountriesCountryGu AnalyticsCountriesCountry = "GU"
	AnalyticsCountriesCountryGt AnalyticsCountriesCountry = "GT"
	AnalyticsCountriesCountryGn AnalyticsCountriesCountry = "GN"
	AnalyticsCountriesCountryGw AnalyticsCountriesCountry = "GW"
	AnalyticsCountriesCountryGy AnalyticsCountriesCountry = "GY"
	AnalyticsCountriesCountryHt AnalyticsCountriesCountry = "HT"
	AnalyticsCountriesCountryHm AnalyticsCountriesCountry = "HM"
	AnalyticsCountriesCountryVa AnalyticsCountriesCountry = "VA"
	AnalyticsCountriesCountryHn AnalyticsCountriesCountry = "HN"
	AnalyticsCountriesCountryHk AnalyticsCountriesCountry = "HK"
	AnalyticsCountriesCountryHu AnalyticsCountriesCountry = "HU"
	AnalyticsCountriesCountryIs AnalyticsCountriesCountry = "IS"
	AnalyticsCountriesCountryIn AnalyticsCountriesCountry = "IN"
	AnalyticsCountriesCountryID AnalyticsCountriesCountry = "ID"
	AnalyticsCountriesCountryIr AnalyticsCountriesCountry = "IR"
	AnalyticsCountriesCountryIq AnalyticsCountriesCountry = "IQ"
	AnalyticsCountriesCountryIe AnalyticsCountriesCountry = "IE"
	AnalyticsCountriesCountryIl AnalyticsCountriesCountry = "IL"
	AnalyticsCountriesCountryIt AnalyticsCountriesCountry = "IT"
	AnalyticsCountriesCountryJm AnalyticsCountriesCountry = "JM"
	AnalyticsCountriesCountryJp AnalyticsCountriesCountry = "JP"
	AnalyticsCountriesCountryJo AnalyticsCountriesCountry = "JO"
	AnalyticsCountriesCountryKz AnalyticsCountriesCountry = "KZ"
	AnalyticsCountriesCountryKe AnalyticsCountriesCountry = "KE"
	AnalyticsCountriesCountryKi AnalyticsCountriesCountry = "KI"
	AnalyticsCountriesCountryKp AnalyticsCountriesCountry = "KP"
	AnalyticsCountriesCountryKr AnalyticsCountriesCountry = "KR"
	AnalyticsCountriesCountryKw AnalyticsCountriesCountry = "KW"
	AnalyticsCountriesCountryKg AnalyticsCountriesCountry = "KG"
	AnalyticsCountriesCountryLa AnalyticsCountriesCountry = "LA"
	AnalyticsCountriesCountryLv AnalyticsCountriesCountry = "LV"
	AnalyticsCountriesCountryLb AnalyticsCountriesCountry = "LB"
	AnalyticsCountriesCountryLs AnalyticsCountriesCountry = "LS"
	AnalyticsCountriesCountryLr AnalyticsCountriesCountry = "LR"
	AnalyticsCountriesCountryLy AnalyticsCountriesCountry = "LY"
	AnalyticsCountriesCountryLi AnalyticsCountriesCountry = "LI"
	AnalyticsCountriesCountryLt AnalyticsCountriesCountry = "LT"
	AnalyticsCountriesCountryLu AnalyticsCountriesCountry = "LU"
	AnalyticsCountriesCountryMo AnalyticsCountriesCountry = "MO"
	AnalyticsCountriesCountryMg AnalyticsCountriesCountry = "MG"
	AnalyticsCountriesCountryMw AnalyticsCountriesCountry = "MW"
	AnalyticsCountriesCountryMy AnalyticsCountriesCountry = "MY"
	AnalyticsCountriesCountryMv AnalyticsCountriesCountry = "MV"
	AnalyticsCountriesCountryMl AnalyticsCountriesCountry = "ML"
	AnalyticsCountriesCountryMt AnalyticsCountriesCountry = "MT"
	AnalyticsCountriesCountryMh AnalyticsCountriesCountry = "MH"
	AnalyticsCountriesCountryMq AnalyticsCountriesCountry = "MQ"
	AnalyticsCountriesCountryMr AnalyticsCountriesCountry = "MR"
	AnalyticsCountriesCountryMu AnalyticsCountriesCountry = "MU"
	AnalyticsCountriesCountryYt AnalyticsCountriesCountry = "YT"
	AnalyticsCountriesCountryMx AnalyticsCountriesCountry = "MX"
	AnalyticsCountriesCountryFm AnalyticsCountriesCountry = "FM"
	AnalyticsCountriesCountryMd AnalyticsCountriesCountry = "MD"
	AnalyticsCountriesCountryMc AnalyticsCountriesCountry = "MC"
	AnalyticsCountriesCountryMn AnalyticsCountriesCountry = "MN"
	AnalyticsCountriesCountryMs AnalyticsCountriesCountry = "MS"
	AnalyticsCountriesCountryMa AnalyticsCountriesCountry = "MA"
	AnalyticsCountriesCountryMz AnalyticsCountriesCountry = "MZ"
	AnalyticsCountriesCountryMm AnalyticsCountriesCountry = "MM"
	AnalyticsCountriesCountryNa AnalyticsCountriesCountry = "NA"
	AnalyticsCountriesCountryNr AnalyticsCountriesCountry = "NR"
	AnalyticsCountriesCountryNp AnalyticsCountriesCountry = "NP"
	AnalyticsCountriesCountryNl AnalyticsCountriesCountry = "NL"
	AnalyticsCountriesCountryNc AnalyticsCountriesCountry = "NC"
	AnalyticsCountriesCountryNz AnalyticsCountriesCountry = "NZ"
	AnalyticsCountriesCountryNi AnalyticsCountriesCountry = "NI"
	AnalyticsCountriesCountryNe AnalyticsCountriesCountry = "NE"
	AnalyticsCountriesCountryNg AnalyticsCountriesCountry = "NG"
	AnalyticsCountriesCountryNu AnalyticsCountriesCountry = "NU"
	AnalyticsCountriesCountryNf AnalyticsCountriesCountry = "NF"
	AnalyticsCountriesCountryMk AnalyticsCountriesCountry = "MK"
	AnalyticsCountriesCountryMp AnalyticsCountriesCountry = "MP"
	AnalyticsCountriesCountryNo AnalyticsCountriesCountry = "NO"
	AnalyticsCountriesCountryOm AnalyticsCountriesCountry = "OM"
	AnalyticsCountriesCountryPk AnalyticsCountriesCountry = "PK"
	AnalyticsCountriesCountryPw AnalyticsCountriesCountry = "PW"
	AnalyticsCountriesCountryPs AnalyticsCountriesCountry = "PS"
	AnalyticsCountriesCountryPa AnalyticsCountriesCountry = "PA"
	AnalyticsCountriesCountryPg AnalyticsCountriesCountry = "PG"
	AnalyticsCountriesCountryPy AnalyticsCountriesCountry = "PY"
	AnalyticsCountriesCountryPe AnalyticsCountriesCountry = "PE"
	AnalyticsCountriesCountryPh AnalyticsCountriesCountry = "PH"
	AnalyticsCountriesCountryPn AnalyticsCountriesCountry = "PN"
	AnalyticsCountriesCountryPl AnalyticsCountriesCountry = "PL"
	AnalyticsCountriesCountryPt AnalyticsCountriesCountry = "PT"
	AnalyticsCountriesCountryPr AnalyticsCountriesCountry = "PR"
	AnalyticsCountriesCountryQa AnalyticsCountriesCountry = "QA"
	AnalyticsCountriesCountryRe AnalyticsCountriesCountry = "RE"
	AnalyticsCountriesCountryRo AnalyticsCountriesCountry = "RO"
	AnalyticsCountriesCountryRu AnalyticsCountriesCountry = "RU"
	AnalyticsCountriesCountryRw AnalyticsCountriesCountry = "RW"
	AnalyticsCountriesCountrySh AnalyticsCountriesCountry = "SH"
	AnalyticsCountriesCountryKn AnalyticsCountriesCountry = "KN"
	AnalyticsCountriesCountryLc AnalyticsCountriesCountry = "LC"
	AnalyticsCountriesCountryPm AnalyticsCountriesCountry = "PM"
	AnalyticsCountriesCountryVc AnalyticsCountriesCountry = "VC"
	AnalyticsCountriesCountryWs AnalyticsCountriesCountry = "WS"
	AnalyticsCountriesCountrySm AnalyticsCountriesCountry = "SM"
	AnalyticsCountriesCountrySt AnalyticsCountriesCountry = "ST"
	AnalyticsCountriesCountrySa AnalyticsCountriesCountry = "SA"
	AnalyticsCountriesCountrySn AnalyticsCountriesCountry = "SN"
	AnalyticsCountriesCountrySc AnalyticsCountriesCountry = "SC"
	AnalyticsCountriesCountrySl AnalyticsCountriesCountry = "SL"
	AnalyticsCountriesCountrySg AnalyticsCountriesCountry = "SG"
	AnalyticsCountriesCountrySk AnalyticsCountriesCountry = "SK"
	AnalyticsCountriesCountrySi AnalyticsCountriesCountry = "SI"
	AnalyticsCountriesCountrySb AnalyticsCountriesCountry = "SB"
	AnalyticsCountriesCountrySo AnalyticsCountriesCountry = "SO"
	AnalyticsCountriesCountryZa AnalyticsCountriesCountry = "ZA"
	AnalyticsCountriesCountryGs AnalyticsCountriesCountry = "GS"
	AnalyticsCountriesCountryEs AnalyticsCountriesCountry = "ES"
	AnalyticsCountriesCountryLk AnalyticsCountriesCountry = "LK"
	AnalyticsCountriesCountrySd AnalyticsCountriesCountry = "SD"
	AnalyticsCountriesCountrySr AnalyticsCountriesCountry = "SR"
	AnalyticsCountriesCountrySj AnalyticsCountriesCountry = "SJ"
	AnalyticsCountriesCountrySz AnalyticsCountriesCountry = "SZ"
	AnalyticsCountriesCountrySe AnalyticsCountriesCountry = "SE"
	AnalyticsCountriesCountryCh AnalyticsCountriesCountry = "CH"
	AnalyticsCountriesCountrySy AnalyticsCountriesCountry = "SY"
	AnalyticsCountriesCountryTw AnalyticsCountriesCountry = "TW"
	AnalyticsCountriesCountryTj AnalyticsCountriesCountry = "TJ"
	AnalyticsCountriesCountryTz AnalyticsCountriesCountry = "TZ"
	AnalyticsCountriesCountryTh AnalyticsCountriesCountry = "TH"
	AnalyticsCountriesCountryTl AnalyticsCountriesCountry = "TL"
	AnalyticsCountriesCountryTg AnalyticsCountriesCountry = "TG"
	AnalyticsCountriesCountryTk AnalyticsCountriesCountry = "TK"
	AnalyticsCountriesCountryTo AnalyticsCountriesCountry = "TO"
	AnalyticsCountriesCountryTt AnalyticsCountriesCountry = "TT"
	AnalyticsCountriesCountryTn AnalyticsCountriesCountry = "TN"
	AnalyticsCountriesCountryTr AnalyticsCountriesCountry = "TR"
	AnalyticsCountriesCountryTm AnalyticsCountriesCountry = "TM"
	AnalyticsCountriesCountryTc AnalyticsCountriesCountry = "TC"
	AnalyticsCountriesCountryTv AnalyticsCountriesCountry = "TV"
	AnalyticsCountriesCountryUg AnalyticsCountriesCountry = "UG"
	AnalyticsCountriesCountryUa AnalyticsCountriesCountry = "UA"
	AnalyticsCountriesCountryAe AnalyticsCountriesCountry = "AE"
	AnalyticsCountriesCountryGb AnalyticsCountriesCountry = "GB"
	AnalyticsCountriesCountryUs AnalyticsCountriesCountry = "US"
	AnalyticsCountriesCountryUm AnalyticsCountriesCountry = "UM"
	AnalyticsCountriesCountryUy AnalyticsCountriesCountry = "UY"
	AnalyticsCountriesCountryUz AnalyticsCountriesCountry = "UZ"
	AnalyticsCountriesCountryVu AnalyticsCountriesCountry = "VU"
	AnalyticsCountriesCountryVe AnalyticsCountriesCountry = "VE"
	AnalyticsCountriesCountryVn AnalyticsCountriesCountry = "VN"
	AnalyticsCountriesCountryVg AnalyticsCountriesCountry = "VG"
	AnalyticsCountriesCountryVi AnalyticsCountriesCountry = "VI"
	AnalyticsCountriesCountryWf AnalyticsCountriesCountry = "WF"
	AnalyticsCountriesCountryEh AnalyticsCountriesCountry = "EH"
	AnalyticsCountriesCountryYe AnalyticsCountriesCountry = "YE"
	AnalyticsCountriesCountryZm AnalyticsCountriesCountry = "ZM"
	AnalyticsCountriesCountryZw AnalyticsCountriesCountry = "ZW"
	AnalyticsCountriesCountryAx AnalyticsCountriesCountry = "AX"
	AnalyticsCountriesCountryBq AnalyticsCountriesCountry = "BQ"
	AnalyticsCountriesCountryCw AnalyticsCountriesCountry = "CW"
	AnalyticsCountriesCountryGg AnalyticsCountriesCountry = "GG"
	AnalyticsCountriesCountryIm AnalyticsCountriesCountry = "IM"
	AnalyticsCountriesCountryJe AnalyticsCountriesCountry = "JE"
	AnalyticsCountriesCountryMe AnalyticsCountriesCountry = "ME"
	AnalyticsCountriesCountryBl AnalyticsCountriesCountry = "BL"
	AnalyticsCountriesCountryMf AnalyticsCountriesCountry = "MF"
	AnalyticsCountriesCountryRs AnalyticsCountriesCountry = "RS"
	AnalyticsCountriesCountrySx AnalyticsCountriesCountry = "SX"
	AnalyticsCountriesCountrySs AnalyticsCountriesCountry = "SS"
	AnalyticsCountriesCountryXk AnalyticsCountriesCountry = "XK"
)

func (e AnalyticsCountriesCountry) ToPointer() *AnalyticsCountriesCountry {
	return &e
}
func (e *AnalyticsCountriesCountry) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AF":
		fallthrough
	case "AL":
		fallthrough
	case "DZ":
		fallthrough
	case "AS":
		fallthrough
	case "AD":
		fallthrough
	case "AO":
		fallthrough
	case "AI":
		fallthrough
	case "AQ":
		fallthrough
	case "AG":
		fallthrough
	case "AR":
		fallthrough
	case "AM":
		fallthrough
	case "AW":
		fallthrough
	case "AU":
		fallthrough
	case "AT":
		fallthrough
	case "AZ":
		fallthrough
	case "BS":
		fallthrough
	case "BH":
		fallthrough
	case "BD":
		fallthrough
	case "BB":
		fallthrough
	case "BY":
		fallthrough
	case "BE":
		fallthrough
	case "BZ":
		fallthrough
	case "BJ":
		fallthrough
	case "BM":
		fallthrough
	case "BT":
		fallthrough
	case "BO":
		fallthrough
	case "BA":
		fallthrough
	case "BW":
		fallthrough
	case "BV":
		fallthrough
	case "BR":
		fallthrough
	case "IO":
		fallthrough
	case "BN":
		fallthrough
	case "BG":
		fallthrough
	case "BF":
		fallthrough
	case "BI":
		fallthrough
	case "KH":
		fallthrough
	case "CM":
		fallthrough
	case "CA":
		fallthrough
	case "CV":
		fallthrough
	case "KY":
		fallthrough
	case "CF":
		fallthrough
	case "TD":
		fallthrough
	case "CL":
		fallthrough
	case "CN":
		fallthrough
	case "CX":
		fallthrough
	case "CC":
		fallthrough
	case "CO":
		fallthrough
	case "KM":
		fallthrough
	case "CG":
		fallthrough
	case "CD":
		fallthrough
	case "CK":
		fallthrough
	case "CR":
		fallthrough
	case "CI":
		fallthrough
	case "HR":
		fallthrough
	case "CU":
		fallthrough
	case "CY":
		fallthrough
	case "CZ":
		fallthrough
	case "DK":
		fallthrough
	case "DJ":
		fallthrough
	case "DM":
		fallthrough
	case "DO":
		fallthrough
	case "EC":
		fallthrough
	case "EG":
		fallthrough
	case "SV":
		fallthrough
	case "GQ":
		fallthrough
	case "ER":
		fallthrough
	case "EE":
		fallthrough
	case "ET":
		fallthrough
	case "FK":
		fallthrough
	case "FO":
		fallthrough
	case "FJ":
		fallthrough
	case "FI":
		fallthrough
	case "FR":
		fallthrough
	case "GF":
		fallthrough
	case "PF":
		fallthrough
	case "TF":
		fallthrough
	case "GA":
		fallthrough
	case "GM":
		fallthrough
	case "GE":
		fallthrough
	case "DE":
		fallthrough
	case "GH":
		fallthrough
	case "GI":
		fallthrough
	case "GR":
		fallthrough
	case "GL":
		fallthrough
	case "GD":
		fallthrough
	case "GP":
		fallthrough
	case "GU":
		fallthrough
	case "GT":
		fallthrough
	case "GN":
		fallthrough
	case "GW":
		fallthrough
	case "GY":
		fallthrough
	case "HT":
		fallthrough
	case "HM":
		fallthrough
	case "VA":
		fallthrough
	case "HN":
		fallthrough
	case "HK":
		fallthrough
	case "HU":
		fallthrough
	case "IS":
		fallthrough
	case "IN":
		fallthrough
	case "ID":
		fallthrough
	case "IR":
		fallthrough
	case "IQ":
		fallthrough
	case "IE":
		fallthrough
	case "IL":
		fallthrough
	case "IT":
		fallthrough
	case "JM":
		fallthrough
	case "JP":
		fallthrough
	case "JO":
		fallthrough
	case "KZ":
		fallthrough
	case "KE":
		fallthrough
	case "KI":
		fallthrough
	case "KP":
		fallthrough
	case "KR":
		fallthrough
	case "KW":
		fallthrough
	case "KG":
		fallthrough
	case "LA":
		fallthrough
	case "LV":
		fallthrough
	case "LB":
		fallthrough
	case "LS":
		fallthrough
	case "LR":
		fallthrough
	case "LY":
		fallthrough
	case "LI":
		fallthrough
	case "LT":
		fallthrough
	case "LU":
		fallthrough
	case "MO":
		fallthrough
	case "MG":
		fallthrough
	case "MW":
		fallthrough
	case "MY":
		fallthrough
	case "MV":
		fallthrough
	case "ML":
		fallthrough
	case "MT":
		fallthrough
	case "MH":
		fallthrough
	case "MQ":
		fallthrough
	case "MR":
		fallthrough
	case "MU":
		fallthrough
	case "YT":
		fallthrough
	case "MX":
		fallthrough
	case "FM":
		fallthrough
	case "MD":
		fallthrough
	case "MC":
		fallthrough
	case "MN":
		fallthrough
	case "MS":
		fallthrough
	case "MA":
		fallthrough
	case "MZ":
		fallthrough
	case "MM":
		fallthrough
	case "NA":
		fallthrough
	case "NR":
		fallthrough
	case "NP":
		fallthrough
	case "NL":
		fallthrough
	case "NC":
		fallthrough
	case "NZ":
		fallthrough
	case "NI":
		fallthrough
	case "NE":
		fallthrough
	case "NG":
		fallthrough
	case "NU":
		fallthrough
	case "NF":
		fallthrough
	case "MK":
		fallthrough
	case "MP":
		fallthrough
	case "NO":
		fallthrough
	case "OM":
		fallthrough
	case "PK":
		fallthrough
	case "PW":
		fallthrough
	case "PS":
		fallthrough
	case "PA":
		fallthrough
	case "PG":
		fallthrough
	case "PY":
		fallthrough
	case "PE":
		fallthrough
	case "PH":
		fallthrough
	case "PN":
		fallthrough
	case "PL":
		fallthrough
	case "PT":
		fallthrough
	case "PR":
		fallthrough
	case "QA":
		fallthrough
	case "RE":
		fallthrough
	case "RO":
		fallthrough
	case "RU":
		fallthrough
	case "RW":
		fallthrough
	case "SH":
		fallthrough
	case "KN":
		fallthrough
	case "LC":
		fallthrough
	case "PM":
		fallthrough
	case "VC":
		fallthrough
	case "WS":
		fallthrough
	case "SM":
		fallthrough
	case "ST":
		fallthrough
	case "SA":
		fallthrough
	case "SN":
		fallthrough
	case "SC":
		fallthrough
	case "SL":
		fallthrough
	case "SG":
		fallthrough
	case "SK":
		fallthrough
	case "SI":
		fallthrough
	case "SB":
		fallthrough
	case "SO":
		fallthrough
	case "ZA":
		fallthrough
	case "GS":
		fallthrough
	case "ES":
		fallthrough
	case "LK":
		fallthrough
	case "SD":
		fallthrough
	case "SR":
		fallthrough
	case "SJ":
		fallthrough
	case "SZ":
		fallthrough
	case "SE":
		fallthrough
	case "CH":
		fallthrough
	case "SY":
		fallthrough
	case "TW":
		fallthrough
	case "TJ":
		fallthrough
	case "TZ":
		fallthrough
	case "TH":
		fallthrough
	case "TL":
		fallthrough
	case "TG":
		fallthrough
	case "TK":
		fallthrough
	case "TO":
		fallthrough
	case "TT":
		fallthrough
	case "TN":
		fallthrough
	case "TR":
		fallthrough
	case "TM":
		fallthrough
	case "TC":
		fallthrough
	case "TV":
		fallthrough
	case "UG":
		fallthrough
	case "UA":
		fallthrough
	case "AE":
		fallthrough
	case "GB":
		fallthrough
	case "US":
		fallthrough
	case "UM":
		fallthrough
	case "UY":
		fallthrough
	case "UZ":
		fallthrough
	case "VU":
		fallthrough
	case "VE":
		fallthrough
	case "VN":
		fallthrough
	case "VG":
		fallthrough
	case "VI":
		fallthrough
	case "WF":
		fallthrough
	case "EH":
		fallthrough
	case "YE":
		fallthrough
	case "ZM":
		fallthrough
	case "ZW":
		fallthrough
	case "AX":
		fallthrough
	case "BQ":
		fallthrough
	case "CW":
		fallthrough
	case "GG":
		fallthrough
	case "IM":
		fallthrough
	case "JE":
		fallthrough
	case "ME":
		fallthrough
	case "BL":
		fallthrough
	case "MF":
		fallthrough
	case "RS":
		fallthrough
	case "SX":
		fallthrough
	case "SS":
		fallthrough
	case "XK":
		*e = AnalyticsCountriesCountry(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnalyticsCountriesCountry: %v", v)
	}
}

type Region string

const (
	RegionWildcard Region = "*"
)

func (e Region) ToPointer() *Region {
	return &e
}
func (e *Region) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "*":
		*e = Region(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Region: %v", v)
	}
}

type AnalyticsCountriesCity string

const (
	AnalyticsCountriesCityWildcard AnalyticsCountriesCity = "*"
)

func (e AnalyticsCountriesCity) ToPointer() *AnalyticsCountriesCity {
	return &e
}
func (e *AnalyticsCountriesCity) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "*":
		*e = AnalyticsCountriesCity(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnalyticsCountriesCity: %v", v)
	}
}

type AnalyticsCountries struct {
	// The 2-letter ISO 3166-1 country code for the country associated with the location of the user. Learn more: https://d.to/geo
	Country AnalyticsCountriesCountry `json:"country"`
	Region  *Region                   `default:"*" json:"region"`
	City    *AnalyticsCountriesCity   `default:"*" json:"city"`
	// The number of clicks from this country
	Clicks *float64 `default:"0" json:"clicks"`
	// The number of leads from this country
	Leads *float64 `default:"0" json:"leads"`
	// The number of sales from this country
	Sales *float64 `default:"0" json:"sales"`
	// The total amount of sales from this country, in cents
	SaleAmount *float64 `default:"0" json:"saleAmount"`
}

func (a AnalyticsCountries) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnalyticsCountries) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AnalyticsCountries) GetCountry() AnalyticsCountriesCountry {
	if o == nil {
		return AnalyticsCountriesCountry("")
	}
	return o.Country
}

func (o *AnalyticsCountries) GetRegion() *Region {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *AnalyticsCountries) GetCity() *AnalyticsCountriesCity {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *AnalyticsCountries) GetClicks() *float64 {
	if o == nil {
		return nil
	}
	return o.Clicks
}

func (o *AnalyticsCountries) GetLeads() *float64 {
	if o == nil {
		return nil
	}
	return o.Leads
}

func (o *AnalyticsCountries) GetSales() *float64 {
	if o == nil {
		return nil
	}
	return o.Sales
}

func (o *AnalyticsCountries) GetSaleAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.SaleAmount
}
