// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-dub/internal/sdk/internal/utils"
)

// LinkSchemaGeo - Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`. Learn more: https://d.to/geo
type LinkSchemaGeo struct {
	Af *string `json:"AF,omitempty"`
	Al *string `json:"AL,omitempty"`
	Dz *string `json:"DZ,omitempty"`
	As *string `json:"AS,omitempty"`
	Ad *string `json:"AD,omitempty"`
	Ao *string `json:"AO,omitempty"`
	Ai *string `json:"AI,omitempty"`
	Aq *string `json:"AQ,omitempty"`
	Ag *string `json:"AG,omitempty"`
	Ar *string `json:"AR,omitempty"`
	Am *string `json:"AM,omitempty"`
	Aw *string `json:"AW,omitempty"`
	Au *string `json:"AU,omitempty"`
	At *string `json:"AT,omitempty"`
	Az *string `json:"AZ,omitempty"`
	Bs *string `json:"BS,omitempty"`
	Bh *string `json:"BH,omitempty"`
	Bd *string `json:"BD,omitempty"`
	Bb *string `json:"BB,omitempty"`
	By *string `json:"BY,omitempty"`
	Be *string `json:"BE,omitempty"`
	Bz *string `json:"BZ,omitempty"`
	Bj *string `json:"BJ,omitempty"`
	Bm *string `json:"BM,omitempty"`
	Bt *string `json:"BT,omitempty"`
	Bo *string `json:"BO,omitempty"`
	Ba *string `json:"BA,omitempty"`
	Bw *string `json:"BW,omitempty"`
	Bv *string `json:"BV,omitempty"`
	Br *string `json:"BR,omitempty"`
	Io *string `json:"IO,omitempty"`
	Bn *string `json:"BN,omitempty"`
	Bg *string `json:"BG,omitempty"`
	Bf *string `json:"BF,omitempty"`
	Bi *string `json:"BI,omitempty"`
	Kh *string `json:"KH,omitempty"`
	Cm *string `json:"CM,omitempty"`
	Ca *string `json:"CA,omitempty"`
	Cv *string `json:"CV,omitempty"`
	Ky *string `json:"KY,omitempty"`
	Cf *string `json:"CF,omitempty"`
	Td *string `json:"TD,omitempty"`
	Cl *string `json:"CL,omitempty"`
	Cn *string `json:"CN,omitempty"`
	Cx *string `json:"CX,omitempty"`
	Cc *string `json:"CC,omitempty"`
	Co *string `json:"CO,omitempty"`
	Km *string `json:"KM,omitempty"`
	Cg *string `json:"CG,omitempty"`
	Cd *string `json:"CD,omitempty"`
	Ck *string `json:"CK,omitempty"`
	Cr *string `json:"CR,omitempty"`
	Ci *string `json:"CI,omitempty"`
	Hr *string `json:"HR,omitempty"`
	Cu *string `json:"CU,omitempty"`
	Cy *string `json:"CY,omitempty"`
	Cz *string `json:"CZ,omitempty"`
	Dk *string `json:"DK,omitempty"`
	Dj *string `json:"DJ,omitempty"`
	Dm *string `json:"DM,omitempty"`
	Do *string `json:"DO,omitempty"`
	Ec *string `json:"EC,omitempty"`
	Eg *string `json:"EG,omitempty"`
	Sv *string `json:"SV,omitempty"`
	Gq *string `json:"GQ,omitempty"`
	Er *string `json:"ER,omitempty"`
	Ee *string `json:"EE,omitempty"`
	Et *string `json:"ET,omitempty"`
	Fk *string `json:"FK,omitempty"`
	Fo *string `json:"FO,omitempty"`
	Fj *string `json:"FJ,omitempty"`
	Fi *string `json:"FI,omitempty"`
	Fr *string `json:"FR,omitempty"`
	Gf *string `json:"GF,omitempty"`
	Pf *string `json:"PF,omitempty"`
	Tf *string `json:"TF,omitempty"`
	Ga *string `json:"GA,omitempty"`
	Gm *string `json:"GM,omitempty"`
	Ge *string `json:"GE,omitempty"`
	De *string `json:"DE,omitempty"`
	Gh *string `json:"GH,omitempty"`
	Gi *string `json:"GI,omitempty"`
	Gr *string `json:"GR,omitempty"`
	Gl *string `json:"GL,omitempty"`
	Gd *string `json:"GD,omitempty"`
	Gp *string `json:"GP,omitempty"`
	Gu *string `json:"GU,omitempty"`
	Gt *string `json:"GT,omitempty"`
	Gn *string `json:"GN,omitempty"`
	Gw *string `json:"GW,omitempty"`
	Gy *string `json:"GY,omitempty"`
	Ht *string `json:"HT,omitempty"`
	Hm *string `json:"HM,omitempty"`
	Va *string `json:"VA,omitempty"`
	Hn *string `json:"HN,omitempty"`
	Hk *string `json:"HK,omitempty"`
	Hu *string `json:"HU,omitempty"`
	Is *string `json:"IS,omitempty"`
	In *string `json:"IN,omitempty"`
	ID *string `json:"ID,omitempty"`
	Ir *string `json:"IR,omitempty"`
	Iq *string `json:"IQ,omitempty"`
	Ie *string `json:"IE,omitempty"`
	Il *string `json:"IL,omitempty"`
	It *string `json:"IT,omitempty"`
	Jm *string `json:"JM,omitempty"`
	Jp *string `json:"JP,omitempty"`
	Jo *string `json:"JO,omitempty"`
	Kz *string `json:"KZ,omitempty"`
	Ke *string `json:"KE,omitempty"`
	Ki *string `json:"KI,omitempty"`
	Kp *string `json:"KP,omitempty"`
	Kr *string `json:"KR,omitempty"`
	Kw *string `json:"KW,omitempty"`
	Kg *string `json:"KG,omitempty"`
	La *string `json:"LA,omitempty"`
	Lv *string `json:"LV,omitempty"`
	Lb *string `json:"LB,omitempty"`
	Ls *string `json:"LS,omitempty"`
	Lr *string `json:"LR,omitempty"`
	Ly *string `json:"LY,omitempty"`
	Li *string `json:"LI,omitempty"`
	Lt *string `json:"LT,omitempty"`
	Lu *string `json:"LU,omitempty"`
	Mo *string `json:"MO,omitempty"`
	Mg *string `json:"MG,omitempty"`
	Mw *string `json:"MW,omitempty"`
	My *string `json:"MY,omitempty"`
	Mv *string `json:"MV,omitempty"`
	Ml *string `json:"ML,omitempty"`
	Mt *string `json:"MT,omitempty"`
	Mh *string `json:"MH,omitempty"`
	Mq *string `json:"MQ,omitempty"`
	Mr *string `json:"MR,omitempty"`
	Mu *string `json:"MU,omitempty"`
	Yt *string `json:"YT,omitempty"`
	Mx *string `json:"MX,omitempty"`
	Fm *string `json:"FM,omitempty"`
	Md *string `json:"MD,omitempty"`
	Mc *string `json:"MC,omitempty"`
	Mn *string `json:"MN,omitempty"`
	Ms *string `json:"MS,omitempty"`
	Ma *string `json:"MA,omitempty"`
	Mz *string `json:"MZ,omitempty"`
	Mm *string `json:"MM,omitempty"`
	Na *string `json:"NA,omitempty"`
	Nr *string `json:"NR,omitempty"`
	Np *string `json:"NP,omitempty"`
	Nl *string `json:"NL,omitempty"`
	Nc *string `json:"NC,omitempty"`
	Nz *string `json:"NZ,omitempty"`
	Ni *string `json:"NI,omitempty"`
	Ne *string `json:"NE,omitempty"`
	Ng *string `json:"NG,omitempty"`
	Nu *string `json:"NU,omitempty"`
	Nf *string `json:"NF,omitempty"`
	Mk *string `json:"MK,omitempty"`
	Mp *string `json:"MP,omitempty"`
	No *string `json:"NO,omitempty"`
	Om *string `json:"OM,omitempty"`
	Pk *string `json:"PK,omitempty"`
	Pw *string `json:"PW,omitempty"`
	Ps *string `json:"PS,omitempty"`
	Pa *string `json:"PA,omitempty"`
	Pg *string `json:"PG,omitempty"`
	Py *string `json:"PY,omitempty"`
	Pe *string `json:"PE,omitempty"`
	Ph *string `json:"PH,omitempty"`
	Pn *string `json:"PN,omitempty"`
	Pl *string `json:"PL,omitempty"`
	Pt *string `json:"PT,omitempty"`
	Pr *string `json:"PR,omitempty"`
	Qa *string `json:"QA,omitempty"`
	Re *string `json:"RE,omitempty"`
	Ro *string `json:"RO,omitempty"`
	Ru *string `json:"RU,omitempty"`
	Rw *string `json:"RW,omitempty"`
	Sh *string `json:"SH,omitempty"`
	Kn *string `json:"KN,omitempty"`
	Lc *string `json:"LC,omitempty"`
	Pm *string `json:"PM,omitempty"`
	Vc *string `json:"VC,omitempty"`
	Ws *string `json:"WS,omitempty"`
	Sm *string `json:"SM,omitempty"`
	St *string `json:"ST,omitempty"`
	Sa *string `json:"SA,omitempty"`
	Sn *string `json:"SN,omitempty"`
	Sc *string `json:"SC,omitempty"`
	Sl *string `json:"SL,omitempty"`
	Sg *string `json:"SG,omitempty"`
	Sk *string `json:"SK,omitempty"`
	Si *string `json:"SI,omitempty"`
	Sb *string `json:"SB,omitempty"`
	So *string `json:"SO,omitempty"`
	Za *string `json:"ZA,omitempty"`
	Gs *string `json:"GS,omitempty"`
	Es *string `json:"ES,omitempty"`
	Lk *string `json:"LK,omitempty"`
	Sd *string `json:"SD,omitempty"`
	Sr *string `json:"SR,omitempty"`
	Sj *string `json:"SJ,omitempty"`
	Sz *string `json:"SZ,omitempty"`
	Se *string `json:"SE,omitempty"`
	Ch *string `json:"CH,omitempty"`
	Sy *string `json:"SY,omitempty"`
	Tw *string `json:"TW,omitempty"`
	Tj *string `json:"TJ,omitempty"`
	Tz *string `json:"TZ,omitempty"`
	Th *string `json:"TH,omitempty"`
	Tl *string `json:"TL,omitempty"`
	Tg *string `json:"TG,omitempty"`
	Tk *string `json:"TK,omitempty"`
	To *string `json:"TO,omitempty"`
	Tt *string `json:"TT,omitempty"`
	Tn *string `json:"TN,omitempty"`
	Tr *string `json:"TR,omitempty"`
	Tm *string `json:"TM,omitempty"`
	Tc *string `json:"TC,omitempty"`
	Tv *string `json:"TV,omitempty"`
	Ug *string `json:"UG,omitempty"`
	Ua *string `json:"UA,omitempty"`
	Ae *string `json:"AE,omitempty"`
	Gb *string `json:"GB,omitempty"`
	Us *string `json:"US,omitempty"`
	Um *string `json:"UM,omitempty"`
	Uy *string `json:"UY,omitempty"`
	Uz *string `json:"UZ,omitempty"`
	Vu *string `json:"VU,omitempty"`
	Ve *string `json:"VE,omitempty"`
	Vn *string `json:"VN,omitempty"`
	Vg *string `json:"VG,omitempty"`
	Vi *string `json:"VI,omitempty"`
	Wf *string `json:"WF,omitempty"`
	Eh *string `json:"EH,omitempty"`
	Ye *string `json:"YE,omitempty"`
	Zm *string `json:"ZM,omitempty"`
	Zw *string `json:"ZW,omitempty"`
	Ax *string `json:"AX,omitempty"`
	Bq *string `json:"BQ,omitempty"`
	Cw *string `json:"CW,omitempty"`
	Gg *string `json:"GG,omitempty"`
	Im *string `json:"IM,omitempty"`
	Je *string `json:"JE,omitempty"`
	Me *string `json:"ME,omitempty"`
	Bl *string `json:"BL,omitempty"`
	Mf *string `json:"MF,omitempty"`
	Rs *string `json:"RS,omitempty"`
	Sx *string `json:"SX,omitempty"`
	Ss *string `json:"SS,omitempty"`
	Xk *string `json:"XK,omitempty"`
}

func (o *LinkSchemaGeo) GetAf() *string {
	if o == nil {
		return nil
	}
	return o.Af
}

func (o *LinkSchemaGeo) GetAl() *string {
	if o == nil {
		return nil
	}
	return o.Al
}

func (o *LinkSchemaGeo) GetDz() *string {
	if o == nil {
		return nil
	}
	return o.Dz
}

func (o *LinkSchemaGeo) GetAs() *string {
	if o == nil {
		return nil
	}
	return o.As
}

func (o *LinkSchemaGeo) GetAd() *string {
	if o == nil {
		return nil
	}
	return o.Ad
}

func (o *LinkSchemaGeo) GetAo() *string {
	if o == nil {
		return nil
	}
	return o.Ao
}

func (o *LinkSchemaGeo) GetAi() *string {
	if o == nil {
		return nil
	}
	return o.Ai
}

func (o *LinkSchemaGeo) GetAq() *string {
	if o == nil {
		return nil
	}
	return o.Aq
}

func (o *LinkSchemaGeo) GetAg() *string {
	if o == nil {
		return nil
	}
	return o.Ag
}

func (o *LinkSchemaGeo) GetAr() *string {
	if o == nil {
		return nil
	}
	return o.Ar
}

func (o *LinkSchemaGeo) GetAm() *string {
	if o == nil {
		return nil
	}
	return o.Am
}

func (o *LinkSchemaGeo) GetAw() *string {
	if o == nil {
		return nil
	}
	return o.Aw
}

func (o *LinkSchemaGeo) GetAu() *string {
	if o == nil {
		return nil
	}
	return o.Au
}

func (o *LinkSchemaGeo) GetAt() *string {
	if o == nil {
		return nil
	}
	return o.At
}

func (o *LinkSchemaGeo) GetAz() *string {
	if o == nil {
		return nil
	}
	return o.Az
}

func (o *LinkSchemaGeo) GetBs() *string {
	if o == nil {
		return nil
	}
	return o.Bs
}

func (o *LinkSchemaGeo) GetBh() *string {
	if o == nil {
		return nil
	}
	return o.Bh
}

func (o *LinkSchemaGeo) GetBd() *string {
	if o == nil {
		return nil
	}
	return o.Bd
}

func (o *LinkSchemaGeo) GetBb() *string {
	if o == nil {
		return nil
	}
	return o.Bb
}

func (o *LinkSchemaGeo) GetBy() *string {
	if o == nil {
		return nil
	}
	return o.By
}

func (o *LinkSchemaGeo) GetBe() *string {
	if o == nil {
		return nil
	}
	return o.Be
}

func (o *LinkSchemaGeo) GetBz() *string {
	if o == nil {
		return nil
	}
	return o.Bz
}

func (o *LinkSchemaGeo) GetBj() *string {
	if o == nil {
		return nil
	}
	return o.Bj
}

func (o *LinkSchemaGeo) GetBm() *string {
	if o == nil {
		return nil
	}
	return o.Bm
}

func (o *LinkSchemaGeo) GetBt() *string {
	if o == nil {
		return nil
	}
	return o.Bt
}

func (o *LinkSchemaGeo) GetBo() *string {
	if o == nil {
		return nil
	}
	return o.Bo
}

func (o *LinkSchemaGeo) GetBa() *string {
	if o == nil {
		return nil
	}
	return o.Ba
}

func (o *LinkSchemaGeo) GetBw() *string {
	if o == nil {
		return nil
	}
	return o.Bw
}

func (o *LinkSchemaGeo) GetBv() *string {
	if o == nil {
		return nil
	}
	return o.Bv
}

func (o *LinkSchemaGeo) GetBr() *string {
	if o == nil {
		return nil
	}
	return o.Br
}

func (o *LinkSchemaGeo) GetIo() *string {
	if o == nil {
		return nil
	}
	return o.Io
}

func (o *LinkSchemaGeo) GetBn() *string {
	if o == nil {
		return nil
	}
	return o.Bn
}

func (o *LinkSchemaGeo) GetBg() *string {
	if o == nil {
		return nil
	}
	return o.Bg
}

func (o *LinkSchemaGeo) GetBf() *string {
	if o == nil {
		return nil
	}
	return o.Bf
}

func (o *LinkSchemaGeo) GetBi() *string {
	if o == nil {
		return nil
	}
	return o.Bi
}

func (o *LinkSchemaGeo) GetKh() *string {
	if o == nil {
		return nil
	}
	return o.Kh
}

func (o *LinkSchemaGeo) GetCm() *string {
	if o == nil {
		return nil
	}
	return o.Cm
}

func (o *LinkSchemaGeo) GetCa() *string {
	if o == nil {
		return nil
	}
	return o.Ca
}

func (o *LinkSchemaGeo) GetCv() *string {
	if o == nil {
		return nil
	}
	return o.Cv
}

func (o *LinkSchemaGeo) GetKy() *string {
	if o == nil {
		return nil
	}
	return o.Ky
}

func (o *LinkSchemaGeo) GetCf() *string {
	if o == nil {
		return nil
	}
	return o.Cf
}

func (o *LinkSchemaGeo) GetTd() *string {
	if o == nil {
		return nil
	}
	return o.Td
}

func (o *LinkSchemaGeo) GetCl() *string {
	if o == nil {
		return nil
	}
	return o.Cl
}

func (o *LinkSchemaGeo) GetCn() *string {
	if o == nil {
		return nil
	}
	return o.Cn
}

func (o *LinkSchemaGeo) GetCx() *string {
	if o == nil {
		return nil
	}
	return o.Cx
}

func (o *LinkSchemaGeo) GetCc() *string {
	if o == nil {
		return nil
	}
	return o.Cc
}

func (o *LinkSchemaGeo) GetCo() *string {
	if o == nil {
		return nil
	}
	return o.Co
}

func (o *LinkSchemaGeo) GetKm() *string {
	if o == nil {
		return nil
	}
	return o.Km
}

func (o *LinkSchemaGeo) GetCg() *string {
	if o == nil {
		return nil
	}
	return o.Cg
}

func (o *LinkSchemaGeo) GetCd() *string {
	if o == nil {
		return nil
	}
	return o.Cd
}

func (o *LinkSchemaGeo) GetCk() *string {
	if o == nil {
		return nil
	}
	return o.Ck
}

func (o *LinkSchemaGeo) GetCr() *string {
	if o == nil {
		return nil
	}
	return o.Cr
}

func (o *LinkSchemaGeo) GetCi() *string {
	if o == nil {
		return nil
	}
	return o.Ci
}

func (o *LinkSchemaGeo) GetHr() *string {
	if o == nil {
		return nil
	}
	return o.Hr
}

func (o *LinkSchemaGeo) GetCu() *string {
	if o == nil {
		return nil
	}
	return o.Cu
}

func (o *LinkSchemaGeo) GetCy() *string {
	if o == nil {
		return nil
	}
	return o.Cy
}

func (o *LinkSchemaGeo) GetCz() *string {
	if o == nil {
		return nil
	}
	return o.Cz
}

func (o *LinkSchemaGeo) GetDk() *string {
	if o == nil {
		return nil
	}
	return o.Dk
}

func (o *LinkSchemaGeo) GetDj() *string {
	if o == nil {
		return nil
	}
	return o.Dj
}

func (o *LinkSchemaGeo) GetDm() *string {
	if o == nil {
		return nil
	}
	return o.Dm
}

func (o *LinkSchemaGeo) GetDo() *string {
	if o == nil {
		return nil
	}
	return o.Do
}

func (o *LinkSchemaGeo) GetEc() *string {
	if o == nil {
		return nil
	}
	return o.Ec
}

func (o *LinkSchemaGeo) GetEg() *string {
	if o == nil {
		return nil
	}
	return o.Eg
}

func (o *LinkSchemaGeo) GetSv() *string {
	if o == nil {
		return nil
	}
	return o.Sv
}

func (o *LinkSchemaGeo) GetGq() *string {
	if o == nil {
		return nil
	}
	return o.Gq
}

func (o *LinkSchemaGeo) GetEr() *string {
	if o == nil {
		return nil
	}
	return o.Er
}

func (o *LinkSchemaGeo) GetEe() *string {
	if o == nil {
		return nil
	}
	return o.Ee
}

func (o *LinkSchemaGeo) GetEt() *string {
	if o == nil {
		return nil
	}
	return o.Et
}

func (o *LinkSchemaGeo) GetFk() *string {
	if o == nil {
		return nil
	}
	return o.Fk
}

func (o *LinkSchemaGeo) GetFo() *string {
	if o == nil {
		return nil
	}
	return o.Fo
}

func (o *LinkSchemaGeo) GetFj() *string {
	if o == nil {
		return nil
	}
	return o.Fj
}

func (o *LinkSchemaGeo) GetFi() *string {
	if o == nil {
		return nil
	}
	return o.Fi
}

func (o *LinkSchemaGeo) GetFr() *string {
	if o == nil {
		return nil
	}
	return o.Fr
}

func (o *LinkSchemaGeo) GetGf() *string {
	if o == nil {
		return nil
	}
	return o.Gf
}

func (o *LinkSchemaGeo) GetPf() *string {
	if o == nil {
		return nil
	}
	return o.Pf
}

func (o *LinkSchemaGeo) GetTf() *string {
	if o == nil {
		return nil
	}
	return o.Tf
}

func (o *LinkSchemaGeo) GetGa() *string {
	if o == nil {
		return nil
	}
	return o.Ga
}

func (o *LinkSchemaGeo) GetGm() *string {
	if o == nil {
		return nil
	}
	return o.Gm
}

func (o *LinkSchemaGeo) GetGe() *string {
	if o == nil {
		return nil
	}
	return o.Ge
}

func (o *LinkSchemaGeo) GetDe() *string {
	if o == nil {
		return nil
	}
	return o.De
}

func (o *LinkSchemaGeo) GetGh() *string {
	if o == nil {
		return nil
	}
	return o.Gh
}

func (o *LinkSchemaGeo) GetGi() *string {
	if o == nil {
		return nil
	}
	return o.Gi
}

func (o *LinkSchemaGeo) GetGr() *string {
	if o == nil {
		return nil
	}
	return o.Gr
}

func (o *LinkSchemaGeo) GetGl() *string {
	if o == nil {
		return nil
	}
	return o.Gl
}

func (o *LinkSchemaGeo) GetGd() *string {
	if o == nil {
		return nil
	}
	return o.Gd
}

func (o *LinkSchemaGeo) GetGp() *string {
	if o == nil {
		return nil
	}
	return o.Gp
}

func (o *LinkSchemaGeo) GetGu() *string {
	if o == nil {
		return nil
	}
	return o.Gu
}

func (o *LinkSchemaGeo) GetGt() *string {
	if o == nil {
		return nil
	}
	return o.Gt
}

func (o *LinkSchemaGeo) GetGn() *string {
	if o == nil {
		return nil
	}
	return o.Gn
}

func (o *LinkSchemaGeo) GetGw() *string {
	if o == nil {
		return nil
	}
	return o.Gw
}

func (o *LinkSchemaGeo) GetGy() *string {
	if o == nil {
		return nil
	}
	return o.Gy
}

func (o *LinkSchemaGeo) GetHt() *string {
	if o == nil {
		return nil
	}
	return o.Ht
}

func (o *LinkSchemaGeo) GetHm() *string {
	if o == nil {
		return nil
	}
	return o.Hm
}

func (o *LinkSchemaGeo) GetVa() *string {
	if o == nil {
		return nil
	}
	return o.Va
}

func (o *LinkSchemaGeo) GetHn() *string {
	if o == nil {
		return nil
	}
	return o.Hn
}

func (o *LinkSchemaGeo) GetHk() *string {
	if o == nil {
		return nil
	}
	return o.Hk
}

func (o *LinkSchemaGeo) GetHu() *string {
	if o == nil {
		return nil
	}
	return o.Hu
}

func (o *LinkSchemaGeo) GetIs() *string {
	if o == nil {
		return nil
	}
	return o.Is
}

func (o *LinkSchemaGeo) GetIn() *string {
	if o == nil {
		return nil
	}
	return o.In
}

func (o *LinkSchemaGeo) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *LinkSchemaGeo) GetIr() *string {
	if o == nil {
		return nil
	}
	return o.Ir
}

func (o *LinkSchemaGeo) GetIq() *string {
	if o == nil {
		return nil
	}
	return o.Iq
}

func (o *LinkSchemaGeo) GetIe() *string {
	if o == nil {
		return nil
	}
	return o.Ie
}

func (o *LinkSchemaGeo) GetIl() *string {
	if o == nil {
		return nil
	}
	return o.Il
}

func (o *LinkSchemaGeo) GetIt() *string {
	if o == nil {
		return nil
	}
	return o.It
}

func (o *LinkSchemaGeo) GetJm() *string {
	if o == nil {
		return nil
	}
	return o.Jm
}

func (o *LinkSchemaGeo) GetJp() *string {
	if o == nil {
		return nil
	}
	return o.Jp
}

func (o *LinkSchemaGeo) GetJo() *string {
	if o == nil {
		return nil
	}
	return o.Jo
}

func (o *LinkSchemaGeo) GetKz() *string {
	if o == nil {
		return nil
	}
	return o.Kz
}

func (o *LinkSchemaGeo) GetKe() *string {
	if o == nil {
		return nil
	}
	return o.Ke
}

func (o *LinkSchemaGeo) GetKi() *string {
	if o == nil {
		return nil
	}
	return o.Ki
}

func (o *LinkSchemaGeo) GetKp() *string {
	if o == nil {
		return nil
	}
	return o.Kp
}

func (o *LinkSchemaGeo) GetKr() *string {
	if o == nil {
		return nil
	}
	return o.Kr
}

func (o *LinkSchemaGeo) GetKw() *string {
	if o == nil {
		return nil
	}
	return o.Kw
}

func (o *LinkSchemaGeo) GetKg() *string {
	if o == nil {
		return nil
	}
	return o.Kg
}

func (o *LinkSchemaGeo) GetLa() *string {
	if o == nil {
		return nil
	}
	return o.La
}

func (o *LinkSchemaGeo) GetLv() *string {
	if o == nil {
		return nil
	}
	return o.Lv
}

func (o *LinkSchemaGeo) GetLb() *string {
	if o == nil {
		return nil
	}
	return o.Lb
}

func (o *LinkSchemaGeo) GetLs() *string {
	if o == nil {
		return nil
	}
	return o.Ls
}

func (o *LinkSchemaGeo) GetLr() *string {
	if o == nil {
		return nil
	}
	return o.Lr
}

func (o *LinkSchemaGeo) GetLy() *string {
	if o == nil {
		return nil
	}
	return o.Ly
}

func (o *LinkSchemaGeo) GetLi() *string {
	if o == nil {
		return nil
	}
	return o.Li
}

func (o *LinkSchemaGeo) GetLt() *string {
	if o == nil {
		return nil
	}
	return o.Lt
}

func (o *LinkSchemaGeo) GetLu() *string {
	if o == nil {
		return nil
	}
	return o.Lu
}

func (o *LinkSchemaGeo) GetMo() *string {
	if o == nil {
		return nil
	}
	return o.Mo
}

func (o *LinkSchemaGeo) GetMg() *string {
	if o == nil {
		return nil
	}
	return o.Mg
}

func (o *LinkSchemaGeo) GetMw() *string {
	if o == nil {
		return nil
	}
	return o.Mw
}

func (o *LinkSchemaGeo) GetMy() *string {
	if o == nil {
		return nil
	}
	return o.My
}

func (o *LinkSchemaGeo) GetMv() *string {
	if o == nil {
		return nil
	}
	return o.Mv
}

func (o *LinkSchemaGeo) GetMl() *string {
	if o == nil {
		return nil
	}
	return o.Ml
}

func (o *LinkSchemaGeo) GetMt() *string {
	if o == nil {
		return nil
	}
	return o.Mt
}

func (o *LinkSchemaGeo) GetMh() *string {
	if o == nil {
		return nil
	}
	return o.Mh
}

func (o *LinkSchemaGeo) GetMq() *string {
	if o == nil {
		return nil
	}
	return o.Mq
}

func (o *LinkSchemaGeo) GetMr() *string {
	if o == nil {
		return nil
	}
	return o.Mr
}

func (o *LinkSchemaGeo) GetMu() *string {
	if o == nil {
		return nil
	}
	return o.Mu
}

func (o *LinkSchemaGeo) GetYt() *string {
	if o == nil {
		return nil
	}
	return o.Yt
}

func (o *LinkSchemaGeo) GetMx() *string {
	if o == nil {
		return nil
	}
	return o.Mx
}

func (o *LinkSchemaGeo) GetFm() *string {
	if o == nil {
		return nil
	}
	return o.Fm
}

func (o *LinkSchemaGeo) GetMd() *string {
	if o == nil {
		return nil
	}
	return o.Md
}

func (o *LinkSchemaGeo) GetMc() *string {
	if o == nil {
		return nil
	}
	return o.Mc
}

func (o *LinkSchemaGeo) GetMn() *string {
	if o == nil {
		return nil
	}
	return o.Mn
}

func (o *LinkSchemaGeo) GetMs() *string {
	if o == nil {
		return nil
	}
	return o.Ms
}

func (o *LinkSchemaGeo) GetMa() *string {
	if o == nil {
		return nil
	}
	return o.Ma
}

func (o *LinkSchemaGeo) GetMz() *string {
	if o == nil {
		return nil
	}
	return o.Mz
}

func (o *LinkSchemaGeo) GetMm() *string {
	if o == nil {
		return nil
	}
	return o.Mm
}

func (o *LinkSchemaGeo) GetNa() *string {
	if o == nil {
		return nil
	}
	return o.Na
}

func (o *LinkSchemaGeo) GetNr() *string {
	if o == nil {
		return nil
	}
	return o.Nr
}

func (o *LinkSchemaGeo) GetNp() *string {
	if o == nil {
		return nil
	}
	return o.Np
}

func (o *LinkSchemaGeo) GetNl() *string {
	if o == nil {
		return nil
	}
	return o.Nl
}

func (o *LinkSchemaGeo) GetNc() *string {
	if o == nil {
		return nil
	}
	return o.Nc
}

func (o *LinkSchemaGeo) GetNz() *string {
	if o == nil {
		return nil
	}
	return o.Nz
}

func (o *LinkSchemaGeo) GetNi() *string {
	if o == nil {
		return nil
	}
	return o.Ni
}

func (o *LinkSchemaGeo) GetNe() *string {
	if o == nil {
		return nil
	}
	return o.Ne
}

func (o *LinkSchemaGeo) GetNg() *string {
	if o == nil {
		return nil
	}
	return o.Ng
}

func (o *LinkSchemaGeo) GetNu() *string {
	if o == nil {
		return nil
	}
	return o.Nu
}

func (o *LinkSchemaGeo) GetNf() *string {
	if o == nil {
		return nil
	}
	return o.Nf
}

func (o *LinkSchemaGeo) GetMk() *string {
	if o == nil {
		return nil
	}
	return o.Mk
}

func (o *LinkSchemaGeo) GetMp() *string {
	if o == nil {
		return nil
	}
	return o.Mp
}

func (o *LinkSchemaGeo) GetNo() *string {
	if o == nil {
		return nil
	}
	return o.No
}

func (o *LinkSchemaGeo) GetOm() *string {
	if o == nil {
		return nil
	}
	return o.Om
}

func (o *LinkSchemaGeo) GetPk() *string {
	if o == nil {
		return nil
	}
	return o.Pk
}

func (o *LinkSchemaGeo) GetPw() *string {
	if o == nil {
		return nil
	}
	return o.Pw
}

func (o *LinkSchemaGeo) GetPs() *string {
	if o == nil {
		return nil
	}
	return o.Ps
}

func (o *LinkSchemaGeo) GetPa() *string {
	if o == nil {
		return nil
	}
	return o.Pa
}

func (o *LinkSchemaGeo) GetPg() *string {
	if o == nil {
		return nil
	}
	return o.Pg
}

func (o *LinkSchemaGeo) GetPy() *string {
	if o == nil {
		return nil
	}
	return o.Py
}

func (o *LinkSchemaGeo) GetPe() *string {
	if o == nil {
		return nil
	}
	return o.Pe
}

func (o *LinkSchemaGeo) GetPh() *string {
	if o == nil {
		return nil
	}
	return o.Ph
}

func (o *LinkSchemaGeo) GetPn() *string {
	if o == nil {
		return nil
	}
	return o.Pn
}

func (o *LinkSchemaGeo) GetPl() *string {
	if o == nil {
		return nil
	}
	return o.Pl
}

func (o *LinkSchemaGeo) GetPt() *string {
	if o == nil {
		return nil
	}
	return o.Pt
}

func (o *LinkSchemaGeo) GetPr() *string {
	if o == nil {
		return nil
	}
	return o.Pr
}

func (o *LinkSchemaGeo) GetQa() *string {
	if o == nil {
		return nil
	}
	return o.Qa
}

func (o *LinkSchemaGeo) GetRe() *string {
	if o == nil {
		return nil
	}
	return o.Re
}

func (o *LinkSchemaGeo) GetRo() *string {
	if o == nil {
		return nil
	}
	return o.Ro
}

func (o *LinkSchemaGeo) GetRu() *string {
	if o == nil {
		return nil
	}
	return o.Ru
}

func (o *LinkSchemaGeo) GetRw() *string {
	if o == nil {
		return nil
	}
	return o.Rw
}

func (o *LinkSchemaGeo) GetSh() *string {
	if o == nil {
		return nil
	}
	return o.Sh
}

func (o *LinkSchemaGeo) GetKn() *string {
	if o == nil {
		return nil
	}
	return o.Kn
}

func (o *LinkSchemaGeo) GetLc() *string {
	if o == nil {
		return nil
	}
	return o.Lc
}

func (o *LinkSchemaGeo) GetPm() *string {
	if o == nil {
		return nil
	}
	return o.Pm
}

func (o *LinkSchemaGeo) GetVc() *string {
	if o == nil {
		return nil
	}
	return o.Vc
}

func (o *LinkSchemaGeo) GetWs() *string {
	if o == nil {
		return nil
	}
	return o.Ws
}

func (o *LinkSchemaGeo) GetSm() *string {
	if o == nil {
		return nil
	}
	return o.Sm
}

func (o *LinkSchemaGeo) GetSt() *string {
	if o == nil {
		return nil
	}
	return o.St
}

func (o *LinkSchemaGeo) GetSa() *string {
	if o == nil {
		return nil
	}
	return o.Sa
}

func (o *LinkSchemaGeo) GetSn() *string {
	if o == nil {
		return nil
	}
	return o.Sn
}

func (o *LinkSchemaGeo) GetSc() *string {
	if o == nil {
		return nil
	}
	return o.Sc
}

func (o *LinkSchemaGeo) GetSl() *string {
	if o == nil {
		return nil
	}
	return o.Sl
}

func (o *LinkSchemaGeo) GetSg() *string {
	if o == nil {
		return nil
	}
	return o.Sg
}

func (o *LinkSchemaGeo) GetSk() *string {
	if o == nil {
		return nil
	}
	return o.Sk
}

func (o *LinkSchemaGeo) GetSi() *string {
	if o == nil {
		return nil
	}
	return o.Si
}

func (o *LinkSchemaGeo) GetSb() *string {
	if o == nil {
		return nil
	}
	return o.Sb
}

func (o *LinkSchemaGeo) GetSo() *string {
	if o == nil {
		return nil
	}
	return o.So
}

func (o *LinkSchemaGeo) GetZa() *string {
	if o == nil {
		return nil
	}
	return o.Za
}

func (o *LinkSchemaGeo) GetGs() *string {
	if o == nil {
		return nil
	}
	return o.Gs
}

func (o *LinkSchemaGeo) GetEs() *string {
	if o == nil {
		return nil
	}
	return o.Es
}

func (o *LinkSchemaGeo) GetLk() *string {
	if o == nil {
		return nil
	}
	return o.Lk
}

func (o *LinkSchemaGeo) GetSd() *string {
	if o == nil {
		return nil
	}
	return o.Sd
}

func (o *LinkSchemaGeo) GetSr() *string {
	if o == nil {
		return nil
	}
	return o.Sr
}

func (o *LinkSchemaGeo) GetSj() *string {
	if o == nil {
		return nil
	}
	return o.Sj
}

func (o *LinkSchemaGeo) GetSz() *string {
	if o == nil {
		return nil
	}
	return o.Sz
}

func (o *LinkSchemaGeo) GetSe() *string {
	if o == nil {
		return nil
	}
	return o.Se
}

func (o *LinkSchemaGeo) GetCh() *string {
	if o == nil {
		return nil
	}
	return o.Ch
}

func (o *LinkSchemaGeo) GetSy() *string {
	if o == nil {
		return nil
	}
	return o.Sy
}

func (o *LinkSchemaGeo) GetTw() *string {
	if o == nil {
		return nil
	}
	return o.Tw
}

func (o *LinkSchemaGeo) GetTj() *string {
	if o == nil {
		return nil
	}
	return o.Tj
}

func (o *LinkSchemaGeo) GetTz() *string {
	if o == nil {
		return nil
	}
	return o.Tz
}

func (o *LinkSchemaGeo) GetTh() *string {
	if o == nil {
		return nil
	}
	return o.Th
}

func (o *LinkSchemaGeo) GetTl() *string {
	if o == nil {
		return nil
	}
	return o.Tl
}

func (o *LinkSchemaGeo) GetTg() *string {
	if o == nil {
		return nil
	}
	return o.Tg
}

func (o *LinkSchemaGeo) GetTk() *string {
	if o == nil {
		return nil
	}
	return o.Tk
}

func (o *LinkSchemaGeo) GetTo() *string {
	if o == nil {
		return nil
	}
	return o.To
}

func (o *LinkSchemaGeo) GetTt() *string {
	if o == nil {
		return nil
	}
	return o.Tt
}

func (o *LinkSchemaGeo) GetTn() *string {
	if o == nil {
		return nil
	}
	return o.Tn
}

func (o *LinkSchemaGeo) GetTr() *string {
	if o == nil {
		return nil
	}
	return o.Tr
}

func (o *LinkSchemaGeo) GetTm() *string {
	if o == nil {
		return nil
	}
	return o.Tm
}

func (o *LinkSchemaGeo) GetTc() *string {
	if o == nil {
		return nil
	}
	return o.Tc
}

func (o *LinkSchemaGeo) GetTv() *string {
	if o == nil {
		return nil
	}
	return o.Tv
}

func (o *LinkSchemaGeo) GetUg() *string {
	if o == nil {
		return nil
	}
	return o.Ug
}

func (o *LinkSchemaGeo) GetUa() *string {
	if o == nil {
		return nil
	}
	return o.Ua
}

func (o *LinkSchemaGeo) GetAe() *string {
	if o == nil {
		return nil
	}
	return o.Ae
}

func (o *LinkSchemaGeo) GetGb() *string {
	if o == nil {
		return nil
	}
	return o.Gb
}

func (o *LinkSchemaGeo) GetUs() *string {
	if o == nil {
		return nil
	}
	return o.Us
}

func (o *LinkSchemaGeo) GetUm() *string {
	if o == nil {
		return nil
	}
	return o.Um
}

func (o *LinkSchemaGeo) GetUy() *string {
	if o == nil {
		return nil
	}
	return o.Uy
}

func (o *LinkSchemaGeo) GetUz() *string {
	if o == nil {
		return nil
	}
	return o.Uz
}

func (o *LinkSchemaGeo) GetVu() *string {
	if o == nil {
		return nil
	}
	return o.Vu
}

func (o *LinkSchemaGeo) GetVe() *string {
	if o == nil {
		return nil
	}
	return o.Ve
}

func (o *LinkSchemaGeo) GetVn() *string {
	if o == nil {
		return nil
	}
	return o.Vn
}

func (o *LinkSchemaGeo) GetVg() *string {
	if o == nil {
		return nil
	}
	return o.Vg
}

func (o *LinkSchemaGeo) GetVi() *string {
	if o == nil {
		return nil
	}
	return o.Vi
}

func (o *LinkSchemaGeo) GetWf() *string {
	if o == nil {
		return nil
	}
	return o.Wf
}

func (o *LinkSchemaGeo) GetEh() *string {
	if o == nil {
		return nil
	}
	return o.Eh
}

func (o *LinkSchemaGeo) GetYe() *string {
	if o == nil {
		return nil
	}
	return o.Ye
}

func (o *LinkSchemaGeo) GetZm() *string {
	if o == nil {
		return nil
	}
	return o.Zm
}

func (o *LinkSchemaGeo) GetZw() *string {
	if o == nil {
		return nil
	}
	return o.Zw
}

func (o *LinkSchemaGeo) GetAx() *string {
	if o == nil {
		return nil
	}
	return o.Ax
}

func (o *LinkSchemaGeo) GetBq() *string {
	if o == nil {
		return nil
	}
	return o.Bq
}

func (o *LinkSchemaGeo) GetCw() *string {
	if o == nil {
		return nil
	}
	return o.Cw
}

func (o *LinkSchemaGeo) GetGg() *string {
	if o == nil {
		return nil
	}
	return o.Gg
}

func (o *LinkSchemaGeo) GetIm() *string {
	if o == nil {
		return nil
	}
	return o.Im
}

func (o *LinkSchemaGeo) GetJe() *string {
	if o == nil {
		return nil
	}
	return o.Je
}

func (o *LinkSchemaGeo) GetMe() *string {
	if o == nil {
		return nil
	}
	return o.Me
}

func (o *LinkSchemaGeo) GetBl() *string {
	if o == nil {
		return nil
	}
	return o.Bl
}

func (o *LinkSchemaGeo) GetMf() *string {
	if o == nil {
		return nil
	}
	return o.Mf
}

func (o *LinkSchemaGeo) GetRs() *string {
	if o == nil {
		return nil
	}
	return o.Rs
}

func (o *LinkSchemaGeo) GetSx() *string {
	if o == nil {
		return nil
	}
	return o.Sx
}

func (o *LinkSchemaGeo) GetSs() *string {
	if o == nil {
		return nil
	}
	return o.Ss
}

func (o *LinkSchemaGeo) GetXk() *string {
	if o == nil {
		return nil
	}
	return o.Xk
}

type LinkSchemaTestVariant struct {
	URL        string  `json:"url"`
	Percentage float64 `json:"percentage"`
}

func (o *LinkSchemaTestVariant) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *LinkSchemaTestVariant) GetPercentage() float64 {
	if o == nil {
		return 0.0
	}
	return o.Percentage
}

type LinkSchema struct {
	// The unique ID of the short link.
	ID string `json:"id"`
	// The domain of the short link. If not provided, the primary domain for the workspace will be used (or `dub.sh` if the workspace has no domains).
	Domain string `json:"domain"`
	// The short link slug. If not provided, a random 7-character slug will be generated.
	Key string `json:"key"`
	// The destination URL of the short link.
	URL string `json:"url"`
	// Whether to track conversions for the short link.
	TrackConversion *bool `default:"false" json:"trackConversion"`
	// The ID of the link in your database. If set, it can be used to identify the link in future API requests (must be prefixed with 'ext_' when passed as a query parameter). This key is unique across your workspace.
	ExternalID *string `json:"externalId"`
	// The ID of the tenant that created the link inside your system. If set, it can be used to fetch all links for a tenant.
	TenantID *string `json:"tenantId"`
	// The ID of the program the short link is associated with.
	ProgramID *string `json:"programId"`
	// The ID of the partner the short link is associated with.
	PartnerID *string `json:"partnerId"`
	// Whether the short link is archived.
	Archived *bool `default:"false" json:"archived"`
	// The date and time when the short link will expire in ISO-8601 format.
	ExpiresAt *string `json:"expiresAt"`
	// The URL to redirect to when the short link has expired.
	ExpiredURL *string `json:"expiredUrl"`
	// The password required to access the destination URL of the short link.
	Password *string `json:"password"`
	// Whether the short link uses Custom Link Previews feature.
	Proxy *bool `default:"false" json:"proxy"`
	// The title of the short link. Will be used for Custom Link Previews if `proxy` is true.
	Title *string `json:"title"`
	// The description of the short link. Will be used for Custom Link Previews if `proxy` is true.
	Description *string `json:"description"`
	// The image of the short link. Will be used for Custom Link Previews if `proxy` is true.
	Image *string `json:"image"`
	// The custom link preview video (og:video). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
	Video *string `json:"video"`
	// Whether the short link uses link cloaking.
	Rewrite *bool `default:"false" json:"rewrite"`
	// Whether to allow search engines to index the short link.
	DoIndex *bool `default:"false" json:"doIndex"`
	// The iOS destination URL for the short link for iOS device targeting.
	Ios *string `json:"ios"`
	// The Android destination URL for the short link for Android device targeting.
	Android *string `json:"android"`
	// Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`. Learn more: https://d.to/geo
	Geo *LinkSchemaGeo `json:"geo"`
	// Whether the short link's stats are publicly accessible.
	PublicStats *bool `default:"false" json:"publicStats"`
	// The unique ID of the tag assigned to the short link. This field is deprecated – use `tags` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	TagID *string `json:"tagId"`
	// The tags assigned to the short link.
	Tags []TagSchema `json:"tags"`
	// The unique ID of the folder assigned to the short link.
	FolderID *string `json:"folderId"`
	// The IDs of the webhooks that the short link is associated with.
	WebhookIds []string `json:"webhookIds"`
	// The comments for the short link.
	Comments *string `json:"comments"`
	// The full URL of the short link, including the https protocol (e.g. `https://dub.sh/try`).
	ShortLink string `json:"shortLink"`
	// The full URL of the QR code for the short link (e.g. `https://api.dub.co/qr?url=https://dub.sh/try`).
	QrCode string `json:"qrCode"`
	// The UTM source of the short link.
	UtmSource *string `json:"utm_source"`
	// The UTM medium of the short link.
	UtmMedium *string `json:"utm_medium"`
	// The UTM campaign of the short link.
	UtmCampaign *string `json:"utm_campaign"`
	// The UTM term of the short link.
	UtmTerm *string `json:"utm_term"`
	// The UTM content of the short link.
	UtmContent *string `json:"utm_content"`
	// An array of A/B test URLs and the percentage of traffic to send to each URL.
	TestVariants []LinkSchemaTestVariant `json:"testVariants,omitempty"`
	// The date and time when the tests started.
	TestStartedAt *string `json:"testStartedAt,omitempty"`
	// The date and time when the tests were or will be completed.
	TestCompletedAt *string `json:"testCompletedAt,omitempty"`
	// The user ID of the creator of the short link.
	UserID *string `json:"userId"`
	// The workspace ID of the short link.
	WorkspaceID string `json:"workspaceId"`
	// The number of clicks on the short link.
	Clicks *float64 `default:"0" json:"clicks"`
	// The date and time when the short link was last clicked.
	LastClicked *string `json:"lastClicked"`
	// The number of leads the short links has generated.
	Leads *float64 `default:"0" json:"leads"`
	// The number of sales the short links has generated.
	Sales *float64 `default:"0" json:"sales"`
	// The total dollar amount of sales the short links has generated (in cents).
	SaleAmount *float64 `default:"0" json:"saleAmount"`
	// The date and time when the short link was created.
	CreatedAt string `json:"createdAt"`
	// The date and time when the short link was last updated.
	UpdatedAt string `json:"updatedAt"`
	// The project ID of the short link. This field is deprecated – use `workspaceId` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ProjectID  string  `json:"projectId"`
	Identifier *string `json:"identifier,omitempty"`
}

func (l LinkSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LinkSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *LinkSchema) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *LinkSchema) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}

func (o *LinkSchema) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *LinkSchema) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *LinkSchema) GetTrackConversion() *bool {
	if o == nil {
		return nil
	}
	return o.TrackConversion
}

func (o *LinkSchema) GetExternalID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalID
}

func (o *LinkSchema) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *LinkSchema) GetProgramID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramID
}

func (o *LinkSchema) GetPartnerID() *string {
	if o == nil {
		return nil
	}
	return o.PartnerID
}

func (o *LinkSchema) GetArchived() *bool {
	if o == nil {
		return nil
	}
	return o.Archived
}

func (o *LinkSchema) GetExpiresAt() *string {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}

func (o *LinkSchema) GetExpiredURL() *string {
	if o == nil {
		return nil
	}
	return o.ExpiredURL
}

func (o *LinkSchema) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *LinkSchema) GetProxy() *bool {
	if o == nil {
		return nil
	}
	return o.Proxy
}

func (o *LinkSchema) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *LinkSchema) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *LinkSchema) GetImage() *string {
	if o == nil {
		return nil
	}
	return o.Image
}

func (o *LinkSchema) GetVideo() *string {
	if o == nil {
		return nil
	}
	return o.Video
}

func (o *LinkSchema) GetRewrite() *bool {
	if o == nil {
		return nil
	}
	return o.Rewrite
}

func (o *LinkSchema) GetDoIndex() *bool {
	if o == nil {
		return nil
	}
	return o.DoIndex
}

func (o *LinkSchema) GetIos() *string {
	if o == nil {
		return nil
	}
	return o.Ios
}

func (o *LinkSchema) GetAndroid() *string {
	if o == nil {
		return nil
	}
	return o.Android
}

func (o *LinkSchema) GetGeo() *LinkSchemaGeo {
	if o == nil {
		return nil
	}
	return o.Geo
}

func (o *LinkSchema) GetPublicStats() *bool {
	if o == nil {
		return nil
	}
	return o.PublicStats
}

func (o *LinkSchema) GetTagID() *string {
	if o == nil {
		return nil
	}
	return o.TagID
}

func (o *LinkSchema) GetTags() []TagSchema {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *LinkSchema) GetFolderID() *string {
	if o == nil {
		return nil
	}
	return o.FolderID
}

func (o *LinkSchema) GetWebhookIds() []string {
	if o == nil {
		return []string{}
	}
	return o.WebhookIds
}

func (o *LinkSchema) GetComments() *string {
	if o == nil {
		return nil
	}
	return o.Comments
}

func (o *LinkSchema) GetShortLink() string {
	if o == nil {
		return ""
	}
	return o.ShortLink
}

func (o *LinkSchema) GetQrCode() string {
	if o == nil {
		return ""
	}
	return o.QrCode
}

func (o *LinkSchema) GetUtmSource() *string {
	if o == nil {
		return nil
	}
	return o.UtmSource
}

func (o *LinkSchema) GetUtmMedium() *string {
	if o == nil {
		return nil
	}
	return o.UtmMedium
}

func (o *LinkSchema) GetUtmCampaign() *string {
	if o == nil {
		return nil
	}
	return o.UtmCampaign
}

func (o *LinkSchema) GetUtmTerm() *string {
	if o == nil {
		return nil
	}
	return o.UtmTerm
}

func (o *LinkSchema) GetUtmContent() *string {
	if o == nil {
		return nil
	}
	return o.UtmContent
}

func (o *LinkSchema) GetTestVariants() []LinkSchemaTestVariant {
	if o == nil {
		return nil
	}
	return o.TestVariants
}

func (o *LinkSchema) GetTestStartedAt() *string {
	if o == nil {
		return nil
	}
	return o.TestStartedAt
}

func (o *LinkSchema) GetTestCompletedAt() *string {
	if o == nil {
		return nil
	}
	return o.TestCompletedAt
}

func (o *LinkSchema) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *LinkSchema) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *LinkSchema) GetClicks() *float64 {
	if o == nil {
		return nil
	}
	return o.Clicks
}

func (o *LinkSchema) GetLastClicked() *string {
	if o == nil {
		return nil
	}
	return o.LastClicked
}

func (o *LinkSchema) GetLeads() *float64 {
	if o == nil {
		return nil
	}
	return o.Leads
}

func (o *LinkSchema) GetSales() *float64 {
	if o == nil {
		return nil
	}
	return o.Sales
}

func (o *LinkSchema) GetSaleAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.SaleAmount
}

func (o *LinkSchema) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *LinkSchema) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *LinkSchema) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *LinkSchema) GetIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.Identifier
}
